### ISSUE TITLE
As a developer, having a npo02__Async_Household_Naming__c setting that is not being used is confusing

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1217]
We should consider deprecating it. Then we could remove the HH_HouseholdNaming.FutureUpdateNames method. This method is called only if npo02__Households_Settings__c.npo02__Async_Household_Naming__c
is set to true. However, there doesn't seem to be a way to configure this setting through the UI.

If we make this change, we need to consider what to do for those orgs that have it set to true (we see errors in the LMO from orgs that have it set to true - for example, some of the errors coming from Children's Tumor Foundation).

DH: Make sure we think this can be achieved thru TDTM trigger handler changes.  What about old orgs who might be using this?

**Comment by davidhabib** [comment]
- I believe we have fixed our code so errors during Future methods does get logged.
- I have verified through manual testing that with this setting turned on, an invalid name spec will log its error in the error log.
- I have found that there are other callers of UpdateNamesFuture(), so we wouldn't remove the future method even if we removed the setting.
- Since this setting has been around from NPSP 2.0, I am concerned we will do more harm than good if we remove it, and it turns out some orgs had a real scenario that required it.
- We continue to not include it on the NPSP Settings page, so there is no issue with having to document it or explain it to users.

Given all this, I propose we leave it as is.
@ceiroa @kbromer do you guys agree?

**Comment by ceiroa** [comment]
I'm ok leaving it like that, now that we have error handling in the FutureUpdateNames method. 

It'll be even less critical to fix this once we have https://github.com/SalesforceFoundation/Cumulus/issues/1218 fixed.

Maybe we should add a note in the npo02__Async_Household_Naming__c description saying that this is not the recommended way to do it anymore?
