### ISSUE TITLE
As a developer, I want to test the API from managed code on a separate package

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1251]
We are separating the original ticket into two, as this case can only be tested once the API is included in a production release (see comment below).

**Comment by ceiroa** [comment]
I have extensively tested case A, and created an app that provides examples of how to use it: https://github.com/SalesforceFoundation/NPSP-API-Examples

@jlantz ~ I have tested running the updatePackageXml and deployWithoutTest targets, and it all works. Let me know what else, if anything, you think we should do here. I'd also be happy to hear your thoughts on package naming, or any other conventions.

Case B cannot be tested yet, as you cannot upload a package that depends on another package. Thus we first need to accept the pull request https://github.com/SalesforceFoundation/Cumulus/pull/1242, and then create the NPSP-API-Examples package once Cumulus contains the API in a production version. However, I'm pretty confident it should all work.

![screen shot 2015-01-21 at 3 23 57 pm](https://cloud.githubusercontent.com/assets/1894238/5846058/70e9bb22-a186-11e4-9f12-42d68dbc5b7c.png)

**Comment by ceiroa** [comment]
We can test this issue now by creating a managed package from https://github.com/SalesforceFoundation/NPSP-API-Examples. The version that contains the API (3.32) has been released: https://login.salesforce.com/packaging/installPackage.apexp?p0=04ti0000000gPr2

**Comment by ceiroa** [comment]
I was able to create a managed production version of the NPSP-API-Examples package successfully, though something strange happened. I installed NPSP through the installer in that org, and it seems like it installed v 3.33:

![screen shot 2015-02-06 at 2 35 04 pm](https://cloud.githubusercontent.com/assets/1894238/6087158/c39e13b6-ae0d-11e4-8a04-82d1b03e9a73.png)

This makes v 3.33 the required version to install NPSP-API-Examples. Since that version is not yet available, I cannot install it. Any thoughts, @jlantz?

Another question for @jlantz; does the file 
https://github.com/SalesforceFoundation/NPSP-API-Examples/blob/master/version.properties look correct?

**Comment by ceiroa** [comment]
I have installed the managed production version of https://github.com/SalesforceFoundation/NPSP-API-Examples/ in an org (with NPSP 3.33 and its dependencies installed), and it all works perfectly. I can see and interact with the data from all the pages.

**Comment by njjc** [comment]
Great! We need to get this in front of ISVs and see what other code they might like opened up.
