### ISSUE TITLE
BUG: When using the recurring donation "Resfresh Opportunity" buttons, newly created opps disappear

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1264]
After clicking the recurring donation "Refresh Opportunity" button, newly created opportunity in the related list have been deleted. User needs to refresh the page for a link to the newly created record. Seems like our code may be deleting and recreating opportunities unnecessarily or at the wrong time.

**Comment by davidhabib** [comment]
not sure there is a bug here.  I think the code deletes all non-closed opps for the RD, and then recalculates them.  this was a fix I made, i believe, because it used to do the wrong thing add just add new ones ignoring the old ones.  ideally, we'd have the original page refreshed, but I don't think the button can do anything about that.

**Comment by njjc** [comment]
Interesting. I figured it was being done in some sort of @ future call. Strange that it returns to the original page without updating the links.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.35 (Beta 13) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.35
