### ISSUE TITLE
As a user, I would like to see Soft Credit rollups on the Household, from all my household members.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1296]
hub thread: https://powerofus.force.com/0D58000001nIHhr
summary: most users don't do soft crediting between household members.  instead, they use it for stuff like matching donations or influenced donations.  so they want to see them on the household.  we should consider a whole set of rollups for these, and make sure we have appropriate settings to make this make sense.  not sure what it means for those orgs who are using are default household soft crediting.

**Comment by karenfitton** [comment]
I think what we need is a set of rollups on the account for soft credits on the contact.  The soft credits on the contact work fine but we need it rolled up on the account so that we can provide accurate reporting on hard and soft credits at the account level.   Thanks!   Karen Fitton

**Comment by njjc** [comment]
[Another request for this.](https://powerofus.force.com/0D5800000231QwX)

**Comment by kbromer** [comment]
We'll have to consider how to aggregate this information without double-counting the credits from the individual Contacts too...

**Comment by njjc** [comment]
I wonder if we could do something tricky along the lines of grouping by the OpportunityContactRole field Contact.AccountID

**Comment by kbromer** [comment]
**lurch: attach W-007341

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZPAAY" target="_blank">W-007341</a>

**Comment by AmandaKByrne** [comment]
Me! Me! Me! I want rollups for soft credit on Household Account! (but don't take away from the Contact)

My staff want it all, and they just can't be satisfied until they can segregate a report on the COMBINED TOTAL of 
- a household's cash gifts (PaymentAmount- Grrr multi year pledges as scheduled gifts!)
- inkind gifts (custom Opp field)
- Auction Purchases Deductible Amount (inkind, not cash, but tracked in the Amount field)
- and Soft credit for the Household.
- Don't forget to split up everything as totals for either CCY or LCY
- Oh, and let's add Board Members (Affiliation with Carolina Tiger's org account). 
- Oh, and if you could throw in something so that if they want a mail list of a specific number of addresses, the report can display what ">  total donation value" will give them the right list size?

Not bitter. :)

**Comment by cpolcyn** [comment]
Included in beta release 3.128 (Beta 7)
