### ISSUE TITLE
BUG: In some orgs, Affiliations are not created with an Account's Primary Contact field is specified.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1323]
hub thread https://powerofus.force.com/0D58000001mccZQ

Kalman has granted login access to orgId 00Dj0000000HmbW

I have verified the Affiliation is not created because of the following line 58 in AFFL_Affiliations_TDTM

        } else if (objResult == Schema.Sobjecttype.Account && !hasRunForAccounts) {

I have verified in the debug log that the objResult == Schema.Sobjectype.Account is failing.  How can this be?  The Account trigger passes in Schema.Sobjecttype.Account which makes it to this run method which then compares against the same thing.  Note that Schema.Sobjectype.Account is an object.  Are there some scenarios where the platform may give you different instances of the describe object?  Maybe we should be doing 

if (objResult.getLabel() == 'Account') instead?

**Comment by davidhabib** [comment]
I meant objResult.getName(), not getLabel().

**Comment by davidhabib** [comment]
just reviewed our codebase, and I didn't find any other places that compare objecttypes this way.

In looking at Apex documentation, it seems example comparisons to detect an object are done like:

// Verify that the generic sObject is an Account sObject
System.assert(s.getsObjectType() == Account.sObjectType);

note that this is different since it is comparing Schema.SObjectType's, not Schema.DescribeSObjectResult's.

@kbromer @ceiroa what do you guys think?

**Comment by kbromer** [comment]
That code is probably older than I am.  I'd just update it to the new method and move on.  Could possibly have been surfaced as a change in behavior from API upgrades (maybe even before the 32.0 one) as well

**Comment by ceiroa** [comment]
So the actual trigger (TDTM_Affiliation) will pass npe5__Affiliation__c. sObjectType instead of  Schema.Sobjecttype.npe5__Affiliation__c  then? We may want to replicate this for all other triggers, just to stay consistent.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.33 (Beta 5) and higher
