### ISSUE TITLE
As a developer, test out Duplicate Management with NPSP

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1363]
https://powerofus.force.com/0D58000001pM4wp

**Comment by njjc** [comment]
Duplicate management offers two functions: reporting a duplicate, which expects the user to manually merge it at a later point, or blocking the duplicate insert and alerting the user.

The first case should be identical to a standard merge, and the second case shouldn't hit our code at all. The only case I'm worried about is our code attempting to create a duplicate and being blocked.

I haven't been able to get the new feature to catch a duplicate at all. Still testing.

**Comment by njjc** [comment]
By disabling all triggers in TDTM, the duplicate catching now works. More investigation is required to find out what exactly in our code is preventing the functionality from working.

**Comment by njjc** [comment]
Well, after reenabling all triggers and disabling error handling, duplicate detection worked again. I then reenabled error handling, and duplicate detection still worked. My only hunch is that enabling the rule takes longer than the platform thinks, since it sends us an email to confirm when the new rules is ready, yet it still wasn't working after that.

**Comment by njjc** [comment]
The issue was around the standard email field not being populated by the workflow rules until after the contact is created. Everything about duplicate catching seems to work smoothly, I've created #1368 and #1369 to integrate duplicate catching functionality into the package and template.

**Comment by kbromer** [comment]
Kickass man.
