### ISSUE TITLE
System.NullPointerException

### ISSUE THREAD

**Issue by nadeemat** [SalesforceFoundation/Cumulus#1489]
I am running in to an issue with the NPSP in my production org, the error log contains the following:

Error Type: System.NullPointerException
Full Message: Attempt to de-reference a null object
Stack Trace: Stacktrace available at the time of saving the record - (npsp)

One thing to note here is that our org has a Visualforce page that is exposed via a Salesforce site, which updates a bunch of custom objects and standard objects such as Contacts and Campaign members. Am I missing something here? 

Help/Direction is greatly appreciated.

**Comment by davidhabib** [comment]
We prefer to have unknown problems first posted in the Power of Us Hub in the NPSP chatter group.  This way everyone can help identify the issue.  If it turns out to be a bug in NPSP, then we will enter it in gitHub.  Here's the link: https://powerofus.force.com/0F980000000CjRe
Repost there, and you will get help.
Thanks.
