### ISSUE TITLE
Including Amount field in Custom Opportunity Naming should not show pennies!

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1544]
If you have {!Amount} in your Opp naming rule, it will get rendered as $500.00, which I'm sure all users would prefer seeing as just $500

**Comment by njjc** [comment]
I believe it was @judisohn who wanted the pennies shown consistently!

**Comment by davidhabib** [comment]
really!?

**Comment by njjc** [comment]
From what I recall! Let's see what she says :)

**Comment by judisohn** [comment]
Yes - it was something that was requested of me a few times when I did workflow rules for the name. I think it was because $98.50 displays as $98.5 if you just do TEXT(Amount) which bothered folks, so I suggested to Nic making the 2 decimals.

Maybe only do the 2 decimals if pennies are involved at all?

**Comment by mrbelvedere** [comment]
Included in beta release version 3.40 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.40
