### ISSUE TITLE
BUG: Opportunity Naming is using Household Primary Contact rather than Opportunity Primary Contact

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1549]
Hub thread: https://powerofus.force.com/0D580000026T3hO

Replicated issue in dev org (3.39). This issue was introduced in latest release, as rule set previously (before Attribution was renamed Contact Donations) is behaving correctly. However, new rule set with Contact Donations or Both Attribution is not. When these rules are used, regardless of the Donor, the name is using the Household's Primary Contact.

**Comment by njjc** [comment]
The issue here is that the Contact Id for Role field doesn't get the correct contact Id for secondary household members. I've created an @future job to rename the opportunity after creation, so while the user won't see the correct name immediately after creating it, the opportunity will get the correct name shortly thereafter.

Fixing this behavior will be possible once we implement #1550

**Comment by mrbelvedere** [comment]
Included in beta release version 3.40 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.40
