### ISSUE TITLE
npsp:Too many query rows: 50001

### ISSUE THREAD

**Issue by TannerWells-IdealistConsulting** [SalesforceFoundation/Cumulus#1560]
Error occurs during mass opportunity record insert (~115 records). Appears to be based on the cumulative fields being updated on the contact object (one to one model). Have de-activated Opportunity trigger (RLLP_OppRollup_TDTM) as a workaround. Also tried setting the trigger to async but issue still remains. 

Thanks!

**Comment by davidhabib** [comment]
1. what happens if you reduce your batch insert size to much smaller (say 10 opps)?
2. is this with NPSP 2.0 or 3.0?
3. is this a recent change in behavior (ie, this scenario recently worked and now doesn't?)
4. if using 3.0, is Custom Opportunity Naming turned on?

**Comment by TannerWells-IdealistConsulting** [comment]
Hi David,

1. This is based on a mass insert via the iATS Brickwork application (batch size (200 records) cannot be adjusted). 
2. 3.0
3. iATS Brickwork has a journal download which runs via nightly scheduled Apex. The maximum number of opportunity records inserted per batch run is 200. The number varies and for the date of the issue, ~115 opportunity records were inserted. 
4. No

Let me know if you would like me to send the debug log. I am the lead developer for the iATS Brickwork application. We haven't noticed this error before. Thanks!

**Comment by njjc** [comment]
Opportunities have a lot of associated code, whenever I did data imports I would always reduce the batch size to avoid hitting limits. Why can't you adjust the batch size in your application?

**Comment by davidhabib** [comment]
Hi Tanner, with NPSP there is a lot of functionality and code that gets executed on opportunity insert.  while we strive to make our code efficient as possible, we have never set our bar to be that we should handle batch sizes as large as 200.  We've always told people who run into limits that they should reduce their batch size into the 10's, not 100's, when bulk loading data.  

Now if you are running into a specific scenario that is failing, and you have reviewed our code and found one of our trigger handlers to be too inefficient, we are open to seeing how it could be improved.  But it is going to require some upfront work on your side to identify what you think the issue is.  @kbromer let me know if you disagree. thanks.

**Comment by TannerWells-IdealistConsulting** [comment]
Thanks David. This is a isolated issue so we'll internally look in to just reducing the batch size if the NPSP is installed or the trigger is active. Thanks for the detailed response!
