### ISSUE TITLE
ERROR: npsp.TDTM_Contact: System.LimitException: Apex CPU time limit exceeded when attempting to update Contacts via dataloader.io

### ISSUE THREAD

**Issue by blairsalesforce** [SalesforceFoundation/Cumulus#1608]
Hello,

I have been running into an issue doing mass Contact updates with dataloader.io since last week. We recently updated our nonprofit starter pack to the newest version. Typically, it'll only let me do a subset of whatever data I am trying to update. I get an error almost every time I try. It gets very laborious to have to do the data loads in batches.

I also recently created a bunch of processes in process builder that evaluate contact records and update the account record if the contact is a 1-to-1 (basically, copy over information from the contact to the account record if the contact is a 1-to-1...for Opportunity reports, etc.). I am wondering if these processes are what are clogging things up. Could this be possible? If not, any other ideas?

**Comment by davidhabib** [comment]
Yes, any process flows or workflows you create on Contacts and Accounts will have a negative impact on bulk data loading into those objects.  try deactivating your workflows while doing your bulk imports.  also you should be able to specify a batch size in your import tool (such as the Data Loader or Demand Tools) so you don't have to manually break up your data into batches.  I don't know how dataloader.io handles this.  In the future, please post these type of questions on the Power of Us Hub, rather than directly into gitHub.  thanks.
