### ISSUE TITLE
Suggest renaming 'Grant Deadline' object to 'Deliverable'

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1617]
Brian Pickett (North Peak)
Deliverable management is a great feature (thanks @Sam Knox (501 Commons) and the SF Foundation!), though its usefulness is not limited to grants. Suggest that the language be generalized around "Deliverables" rather than made so specific with "Grant Deadlines."

**Comment by BrightStepTracy** [comment]
Agreed - "Deliverable" is a much more encompassing term, especially when it comes to things like Local/State/Federal government grants.

**Comment by mstark2014** [comment]
Since there is the option to create Record Types on this object, would it make sense for each organization to customize this object with different record types and page layouts for grant deadlines and for program milestones?  Is there any problem with multiple record types in this feature?

**Comment by BrightStepTracy** [comment]
I tend to not like record-typing these kinds of sub-Objects, largely because we're usually dealing with data categorizations rather than separate business processes, since the object itself is already very specialized.

**Comment by mstark2014** [comment]
I understand, although I have found it useful when you want a different page layout for the different record types.  In our org, I have used a custom object for surveys; since we have six different surveys with different questions, I used a different record type for each survey.   In the grant case, there may be very different information you want to keep track of during grant application vs. grant deliverable milestones, especially if the grant is funded based on milestones.  Is there any problem with the feature functionality with multiple record types?

**Comment by BrightStepTracy** [comment]
Shouldn't be - and, that's a great reason to record-type!  This is a pretty basic Object architecture, and the feature enhancement requests would likely be agnostic to them.

**Comment by judisohn** [comment]
While I agree with @BrightStepTracy that right now it doesn't matter if record types are added to the object and that it probably shouldn't matter in future enhancements, I don't think anyone can promise that it will always not matter.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwBAAQ" target="_blank">W-008307</a>

**Comment by jlantz** [comment]
Included in beta release 3.81 (Beta 12)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.81
