### ISSUE TITLE
Recurring Donation Via Data Loader

### ISSUE THREAD

**Issue by poonamkeswani** [SalesforceFoundation/Cumulus#1625]
All,

We just did a data migration and imported around 1500 recurring donation in None Status. The problem is that the system does not create future donations if the data in entered via Data Loader.
If i go and edit the record in Salesforce UI , it creates the future donation in pledged status.
However it does not create them if, I perform a Dry Update on the Recurring Donation.

This is happening in production environment : Org ID : 00D90000000fsEY
I have granted access to Salesforce Foundation.

Below is what we tried.
1) To run the batch
2) Update Next Donation Date on all Recurring Donation.

However still there is no solution.
Can you suggest if its even possible ?

**Comment by poonamkeswani** [comment]
@njjc - Your help here is highly appreciated.
We are facing the issue in Production Environment.

**Comment by poonamkeswani** [comment]
Thanks it got fixed.
I was using Bulk API due to which the trigger i believe was not get executed.
Reduced the batch size and it worked

**Comment by judisohn** [comment]
Hi @poonamkeswani - in the future, feel free to post these things over in the NPSP group on the Power of Us Hub first. That way our team and the community can help you troubleshoot and if it indeed turns out to be a bug or issue that requires a code change in NPSP, then it can be posted here. Thanks and glad you figured it out regardless.
