### ISSUE TITLE
NPSP Error - Sharing Rules

### ISSUE THREAD

**Issue by poonamkeswani** [SalesforceFoundation/Cumulus#1628]
Hello,

We have users in different geographical locations (territories).
In our environment we have the Account/Contact OWD set to Private.
We have further configured Sharing Rules to provide Read/Write access to the users in same territory. 
In a scenario where User A is adding a note contact record owned by User B. Here User A and User B are in the same territory. User A was successfully able to add the note, however they system admin is receiving an email.
Can you suggest why the email is being sent out despite no error to user and no break in functionality

Below is the email
---------------------------------------
Organization: Cambodian Children's Fund Australia Inc.(00D90000000fsEYEAY)
User: nicky@cambodianchildrensfund.org(00590000000t2VgAAI)

Errors:

----------
 Error #1:

Error Type: Other
Error Date: 2015-06-27 01:15:14
Message: "insufficient access rights on object id"
https://ap1.salesforce.com/0019000000jkKW3AAM

Stack Trace:
 null.

**Comment by judisohn** [comment]
Hi @poonamkeswani - if you have access to the Power of Us Hub, please post this question there. In this case, it sounds like it's more of a security-setting issue and I'm sure someone in the System Administrators group can help you troubleshoot further. The error email you received is just NPSP reporting back, and doesn't appear to be an issue directly with NPSP. If it turns out to be something related to NPSP code that needs to change, we can reopen this. 

Thanks for understanding!

**Comment by force2b** [comment]
@poonamkeswani Check out issue #1479 and this related hub post - https://powerofus.force.com/0D580000023095l.
