### ISSUE TITLE
Custom Lead field mapping to Affiliations

### ISSUE THREAD

**Issue by JimBTek** [SalesforceFoundation/Cumulus#1712]
It would be ideal to be able to convert a lead and map custom fields to the Affiliation Object for things like Student, Major, GPA, graduation date, etc.  Just like LinkedIn, where you are Affiliated to an Org and have custom data about that relationship.

This along with my other [issue](https://github.com/SalesforceFoundation/Cumulus/issues/1711) of not being able to re-parent Affiliations makes it impossible to use a web form with NPSP and custom Affiliation data. 

Thanks!!!

**Comment by judisohn** [comment]
Hi @JimBTek This is actually something that is out of the control of the Nonprofit Starter Pack development team. I recommend that you add your use case to this Salesforce Idea: https://success.salesforce.com/ideaView?id=08730000000BrgSAAS 

Note that while what you're trying to achieve is not possible out of the box at this time due to platform limitations, you can work with a developer to create a custom lead conversion experience that might work for you.

**Comment by JimBTek** [comment]
Hi @judisohn appreciate the response and understand. That Idea is a little different. Yeah if these were bigger projects we could consider a custom lead conversion process, thanks for that idea.
