### ISSUE TITLE
Auto Add Campaign Members

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1765]
NSPS Sprint (Fall '15)

Megan Himan megan@brightsteppartners.com
Jordan Baucke jordan.baucke@presencepg.com
Jason Cook jason@sputnikmoment.com
Nic Campbell ncampbell@salesforce.com

Link to description: https://docs.google.com/a/brightsteppartners.com/document/d/1yZZSr4DRv8GmuH1wrQUdY_Oxoj3kOn20LWcBjruG-HU/edit?usp=sharing

**Comment by johnfine** [comment]
If this is the feature 'auto-insert a CampMem record when an Opp is inserted that has non-null in Opp.Campaign', then I just wanted to request that CampMem.Status should be a hasResponded status (not sure exactly what the algorithm would be since the default Status value "Responded" could have been changed).

**Comment by njjc** [comment]
Yep, we're doing non closed/won opps map to the first non-responded stage,
closed/won opps map to the first responded stage, and we're also including
a field to provide whatever stage you want on the opportunity record.

**Comment by johnfine** [comment]
You guys are the best!

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gr8AAA" target="_blank">W-008593</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.55 (Beta 8) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.55
