### ISSUE TITLE
When converting a lead, I may want the opportunity created to be related to a contact's primary affiliation

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1846]
**External Contribution Issue created by @cdcarter**

As a user converting leads, I want the option to create the opportunity on the lead's new primary affiliation instead of on their household, so that I can use leads to track corporate gifts/sponsorships.

On the NPSP lead convert override, we have the option to create a primary affiliation for a contact to the Lead's "Company". A checkbox to also associate the opportunity with that Organization account (though maintaining the OCR) would allow organizations that use Leads to track corporate sponsorship to not have to manually update created opportunities.

**Comment by bethbbc** [comment]
Instead of a checkbox, I suggest a picklist to select which Account to associate the Opportunity with: HH or Affiliated Organization. If it's just a checkbox to "override" the currently-default behaviour, a non-familiar user would not understand that at all, not knowing what the implied default is. A picklist makes it an explicit, clear choice each time. (HH could be default to preserve current default behaviour.)

**Comment by designbybenjamin** [comment]
There is an existing issue that needs to be resolved before this new feature is added - on the NPSP lead override, when the user opts to create an Opportunity, the new Opportunity is automatically associated with the Affiliated Org, not the household. By default, for individuals with a household and an affiliated account I would think a donation should go on the Household, but that is not the case.

**Comment by cdcarter** [comment]
@designbybenjamin -- Current behavior (as of NPSP 3.61 with the npsp__ override in place) an opportunity for a converted lead DOES go to the household. This feature request/pull request gives you the option to choose the affiliated org instead of the household. If you're seeing the opportunity affiliated with the org account instead of the new household, I haven't found that behavior yet. Can you give me clear steps to reproduce?

**Comment by mrbelvedere** [comment]
Included in beta release version 3.62 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.62
