### ISSUE TITLE
Deleting last Contact in a HH Account with Closed-Won Opp --> Anonymous HH Account

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/Cumulus#1875]
If a HH Account has only one Contact, and if there is a Closed/Won Opp whose Contact Role points to that Contact, then if that Contact is deleted, the HH Account remains but is renamed "Anonymous" and the Opp loses its Contact Role.

Issue: There should never be an HH Account with 0 Contacts; can't easily distinguish this Anonymous HH Account from Anonymous HH Accounts due to Deceased Contacts; neither the Opp nor the remaining Anonymous HH Account have the former Contact's name so it is impossible to associate the Opp with the original donor.

The all happens because SF platform prevents delete of an Account that has a Closed/Won Opp.

Proposed change: NPSP should prevent the deletion of a Contact like this and provide an error msg along the lines of "This Contact can;t be deleted because they have at least one Closed/Won Opportunity".

**Comment by judisohn** [comment]
@johnfine We have that already. :-) But you need to go to Setup > Build > Customize > Contacts > Buttons, Links and Actions and click Edit to the left of Delete and change it to the Visualforce page of CON_DeleteContactOverride (the one that has the npsp__ namespace).

In my org, in the situation you describe I get this:

Delete failed. First exception on row 0 with id 0011a000004n72XAAQ; first error: DELETE_FAILED, Your attempt to delete Kelly Tester Household could not be completed because some opportunities in that account were closed won. The opportunities that could not be deleted are shown below.: Kelly Tester Household $80 Donation 12/17/2015 : []
Error is in expression '{!processDelete}' in component <apex:page> in page npsp:con_deletecontactoverride: (npsp)

Not a pretty error, sure - but no data is actually deleted and nothing is changed, which appears to be the behavior you were expecting. I'm going to close this for now, but feel free to add additional comments if needed. Thanks!

**Comment by johnfine** [comment]
Yup, that worked - I missed the POU post about it back in October - my bad!

I would comment that:
* There are two VF pages with similar names to choose from, it would be
nice if possible if there were only one.
* The error message is indeed ugly for a non-sysadmin user; this raises the
question of how much resource to dedicate to making NPSP error handling in
general more end-user friendly.
* This button override is not, as far I can see documented in the NPSP 3.0
upgrade post-install steps.

Would it be worth considering having Health Check check on meta-data
malformations like this one?  is it even possible?

**Comment by judisohn** [comment]
It's on our documentation backlog to upgrade those post-install instructions, which haven't been updated since NPSP 3 was new. I'm not sure if this is possible to cover in Health Check - @davidhabib?

**Comment by davidhabib** [comment]
nope, health check has no way of checking whether overrides are set.


David Habib | Senior Force.com Developer | salesforce.org
