### ISSUE TITLE
Automated Address Rollback

### ISSUE THREAD

**Issue by BrightStepTracy** [SalesforceFoundation/Cumulus#1884]
Restore a Contact/Household (Account) Address to the immediate prior value and delete any newly created Address Object records (restoring the prior Address values in the Contact/Account records).  Should be able to be triggered on a per-record, and en-masse via update action (for high volumes of changed records) Use cases:

* Integrations creating new Address Object records as Contact address fields updated by the integration
* User error
* Batch entry error/updates

**Comment by judisohn** [comment]
I'll be honest, Tracy - while I can see the value here, I have a feeling it's a big lift technically for a narrow situation. User error is a risk in any integration for any field/object, isn't it? Doesn't it make more sense to restore data from backup?

**Comment by BrightStepTracy** [comment]
Well, there's a few issues that I see that this (and similar feature enhancement requests) solve for -

* Backups happen, at most, once a week - and, data can change much more quickly than that and do damage in the intervening time.  Also, restoring from backup is a PITA for even experienced folks, let alone the kinds of SysAdmins to which the NPSP is frequently relegated at many NPOs.  It's a *lot* of work and technical understanding.

* SFDC as a platform is increasingly becoming granular enough to support real power users and distributed administration of key functions, which, at NPOs, helps to solve the problem of when a key single system administrator leaves the organization and takes all of the knowledge about how to work inside of Salesforce (and the NPSP, accordingly) with them.  My personal belief is that we want to be able to empower more users at organizations with more data-critical functions, so that the NPSP can better support the power user, and not lock up all of its data maintenance with SysAdmins alone (and, this is a change in philosophy, I know).

* Lastly, there's an issue of the multiple actors who are now using the NPSP -- The NPSP is growing as a product beyond just its roots in fundraising, and program staff don't interact much at all with Opportunities, but having features and administration devices that substantially enhance Accounts, Contacts, and Campaigns is a big win for them: especially as we also look to an integrated ecosystem of 3rd party tools dependent on these same Objects.  This is as much about providing audit trails (which is easily done with the History) as it is about providing immediate reversal of a problem so that it doesn't quickly propagate throughout an organization's program/integrated ecosystem.

**Comment by judisohn** [comment]
You're right on all points, but it's also necessary to separate the app from the platform in this case. There are about 400 custom fields in NPSP, plus you're even talking about standard fields. I know you're talking about Address fields here, but why just those? The effort versus benefit analysis doesn't balance out here. It would add considerable complexity in order to work around platform challenges, which in the aim to make things easier for users would actually make it more difficult.

NPSP works best in concert with other apps and the entire Salesforce platform. It seems to be a better path to recommend something like Spanning Backup (nicely discounted for nonprofits) which does daily backups if that's a requirement, and "measure twice cut once" best practices. 

If someone is able to design a backup solution specific to NPSP we'd of course review/consider it, but this isn't going to be something that will make it to the top of the pile for internal resources anytime in the foreseeable future.
