### ISSUE TITLE
unexpected results for a 3-way Contact merge

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#1940]
Create 3 Contacts via the API, aaa1, aaa2, and aaa3, with associated values for Mailing Address. Search for them and select them for merging: 

![screen shot 2016-02-11 at 10 49 42 am](https://cloud.githubusercontent.com/assets/204643/12984895/365d98be-d0ad-11e5-9da0-346960025eca.png)

Select aaa2 as the Master record. Select last name of aaa1, city2, country3, etc. See screen shot for exact values. Especially note having selected the Current Address for 1: 

![screen shot 2016-02-11 at 11 21 10 am](https://cloud.githubusercontent.com/assets/204643/12985806/9c103fb4-d0b1-11e5-86c1-6fd2fd2f0850.png)

Click Merge for the records. 
Despite choosing 2 as the master record, the Household Account is 1. Despite choosing a selection of address values from among 1, 2, and 3 records, final address is all values from 1.

![screen shot 2016-02-11 at 11 23 09 am](https://cloud.githubusercontent.com/assets/204643/12985882/e65c5314-d0b1-11e5-837b-213362c7438d.png)

Edit the resulting Contact record. Although the display screen shows all address values as 1, the edit screen for the Contact shows all address values as 2:

![screen shot 2016-02-11 at 11 24 21 am](https://cloud.githubusercontent.com/assets/204643/12985921/0cf54f9e-d0b2-11e5-9e48-6994424d95d9.png)

Summary: I think the Contact Merge page should respect the user's choices, and not overwrite them with values from the (invisible) Current Address record; or if it must do that, it should allow the user to reject those changes before saving.  And regardless of what values appear in the Contact record, there should be no discrepancy between what is shown in the display page and what is shown in the Edit page.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001qFhAAI" target="_blank">W-009324</a>

**Comment by davidhabib** [comment]
OK, there is a lot going on here. 

1. The correct account (from aaa2) was preserved.  You thought it was the wrong account, because it's name got updated since you chose aaa1's lastname to overwrite aaa2's lastname.  I verified it was the correct account.

2. the winning account ends up with address objects from all three accounts, because when you merge the only contact from a household account into another household account, we merge the accounts as well as the contacts.  Our behavior for merging accounts includes bringing along all address objects.

3. the reason you first see one address, and in edit (or if you had refreshed the page) you see another is because our Account Merge code does its fixups (including combining the addresses) in a future call to avoid soql limits.  Unfortunately there is nothing we can do about this.  Future calls occur after Salesforce has rendered the page.  

4. your choosing both a different current address, as well as modifying multiple address fields on the winning contact, creates an ambiguous situation.  We don't deal with this well because I can't even define what it should do.  We can't both set the contact's address fields to the new current address's values, as well as modify the existing contact address fields.  We could potentially put in a code to generate a runtime error for this ambiguous situation, but that feels relatively low priority to me, and I suspect won't come off the backlog anytime soon.  This ambiguous situation ends up confusing the address code, and the contact stays with having the default address of its Household.

5. if you run this scenario again, but this time leave current address with m2 (the winner) but select a mixture of standard address fields from the three contacts, then the merge does successfully end up with 4 addresses (m2's original, m1's default, m3's default, and a new default which is the mixture of address fields you select in the merge).  This is the correct and desirable behavior.

So we are really just left with the weirdness described in #4.  How we want to deal with this ambiguous scenario, and how high priority it is to do, is open to discussion!

@chrismcmahon @mpusto @judisohn @njjc

**Comment by judisohn** [comment]
The only possible solution I can picture here is that we create a brand new address record with the mix of the selected address components. This would only be necessary if address fields are selected from multiple Contacts in the merge. If they're all off the master or all off a single Contact, then that Contact's 'Current Address' should be assumed and not present 'Current Address' as a selectable field in the screen at all. That data is ambiguous since no one can tell what's different between A-00356 and A-00223 anyway from that view.

**Comment by davidhabib** [comment]
maybe I wasn't clear.  we are creating a brand new address correctly, if they do not also change the current address lookup.  are you suggesting that in the scenario of address changes and current address lookup being changed, we just ignore the current address lookup change?

**Comment by judisohn** [comment]
Yes, I'm suggesting that 'Current Address' shouldn't be an option on the merge screen at all. Since it's a radio button, there's no not selecting it and I think that's part of the confusion. So if they leave the 'Current Address' at Master but select address fields from across the other Contacts, then if you are creating a brand new Address record already you are indeed already ignoring 'Current Address' anyway, right?

**Comment by davidhabib** [comment]
I think that would be a good solution to just remove the current address field from the contact merge display.  Chris can just avoid changing it from the master selected contact and continue with his work until this change is done.

**Comment by chrismcmahon** [comment]
+1 to remove the choice of Current Address.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.66 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.66

**Comment by chrismcmahon** [comment]
Update with a note: 

After merging the fix for this issue I continue to encounter a similar issue, but it is intermittent and difficult to reproduce consistently. I discussed it with Jason Bury and we continue to investigate. 

The issue is similar to the original report: in the original report, after choosing disparate values for address, upon merging the Contact detail record had all values from address1, and then those values were overwritten with all values from address2. 

The current intermittent issue is that instead of the Contact detail record having values from address1, the address on the detail record is correct, and displays the choices that the user made. However, sometimes the final address values for the Contact record are being overwritten by values from address2, just as in the original issue report. 

We are not sure why this overwriting of chosen address values with address2 is sometimes triggered and sometimes not.
