### ISSUE TITLE
Double counting opportunity amounts with duplicate OCRs

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/Cumulus#1971]
Currently, if a contact holds two soft credit OCRs on an opportunity (e.g. in a peer-to-peer campaign, a contact may be both Household Member and Fundraiser, if their spouse gives to their campaign), that opportunity's value will be double counted in the soft credit rollups. 

@judisohn writes: 
> Yes, it’s expected… We don’t expect for the same contact to be listed more than once and advise against that. Probably not a bad idea to anticipate that it’s not intended and code rollups to not double count, but right now we don’t do that.

It'd be great if an opportunity was counted once and only once in soft credit rollups, regardless of number of OCRs.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000033WpAAI" target="_blank">W-009492</a>

**Comment by BrightStepTracy** [comment]
This is a bug by my reckoning - there's so few circumstances where organizations would want to double-count soft credit OCR-rollups for a single person, that it requires a more urgent fix.  Otherwise, organizations will be reporting on incorrect rollup totals.

**Comment by davidhabib** [comment]
Given this behavior has been around since Soft Credits were introduced in NPSP 2, I find it hard to prioritize as "urgent".

**Comment by BrightStepTracy** [comment]
NPSP3 has introduced a multitude of soft credit Contact Roles for specific functions over the past 3-4 months, including honor/memorial, matching gifts, and now partial soft credits.  I'd argue that what's changed since NPSP2 is that the likelihood of multiple Contact Roles being assigned to the same person, some of which will now be double-counted, has increased tremendously.  For a long while, the usual suspect soft credits that got automatically assigned were for household members.  Now, there are several processes that could auto-assign them, all of which were introduced very recently.  From a NPO process perspective, I don't know any DD that would intentionally double-count soft credits in a rollup.

**Comment by davidhabib** [comment]
the double counting only occurs for contacts who have no Partial Soft Credits on the Opp, and have duplicate OCR's marked as a soft credit role (Soft Credit, Household Member) on the Opp.  Thus the recent introduction of Partial Soft Credits has not added to the occurrence of this behavior.

**Comment by BrightStepTracy** [comment]
If there's no way double Partial Soft Credits can be ignored, and they don't leverage the Contact Roles for anything that's good to know :)  But, my point remains - we've just leaned heavily on Contact Roles for  the first time in a long while, and this will become more apparent as new Contact Role dependent functions come online for organizations.

**Comment by judisohn** [comment]
Beyond partial soft credit, none of the recent functionality that adds contact roles will add doubles. For example, the honor/memorial functionality specifically avoids dupes. New functions will also be as intelligent. The way dupes happen is through bad data imports and bad data entry which we have no mechanism to prevent. And which as Dave points out, has been around since forever in NPSP. Not that this won't be done, (and it's certainly helped along by Christian's pull request) it just has to get prioritized appropriately.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.76 (Beta 16) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.76
