### ISSUE TITLE
Do not set Custom Naming to 'Name' if Account Name is updated to 'REPLACE'

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2099]
thread started by @cdcarter https://powerofus.force.com/0D58000002jJzVd

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003oxxRAAQ" target="_blank">W-010539</a>

**Comment by njjc** [comment]
Here's the line that needs an extra conditional: https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/HH_HouseholdNaming.cls#L330

**Comment by cdcarter** [comment]
Nic, maybe I'm missing something, but should line 332 *already* be doing this? I don't quite get the point of that branch.

**Comment by njjc** [comment]
I think by design it should do what you're requesting, but in your update case the line 330 condition is true and ends up excluding HH name from being recalculated, so we never get to 332. In 330 we just need to make sure that the name hasn't been set to Label.npo02.NameReplacementText.

The only thing I'm not sure of is if we're already excluding Name from being auto calculated, but then we set the name to Label.npo02.NameReplacementText, should we remove Name from the exclusions and recalculate anyway? I think so. @davidhabib

**Comment by judisohn** [comment]
I think so too @njjc - exactly.

**Comment by njjc** [comment]
@cdcarter do you feel like contributing this fix? Otherwise I can slate it into my next sprint.

**Comment by cdcarter** [comment]
I feel comfortable fixing the if statement around 330 to at least allow this specific scenario to pass through, but your other idea is a little bit more in the weeds of the naming system than I really understand, so if you can get that in the next sprint, that's great.

**Comment by njjc** [comment]
We're actually not releasing to sandbox next week due to being in the in-between period for the summer '16 release, so I believe it will be three weeks from yesterday before you can get it in your customer sandbox. I'm happy to update it by then, I'll add it to my backlog.

**Comment by cdcarter** [comment]
Great. Thank you so much!

**Comment by mrbelvedere** [comment]
Included in beta release version 3.75 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.75
