### ISSUE TITLE
In Data Importer, if Campaign is specified and record fails to import, a dup Campaign record is created

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/Cumulus#2162]
Create and import a DI template file in which there is a row of data where:
- Donation Amount is specified  
- Campaign matches an existing SF Campaign
- Something about the row will cause the DI import to fail (ex: Contact First Name and Last Name will fail SF duplicate management rules).

Issue: After DI import, the failed record causes DI to create a duplicate Campaign record whose name is the value from the Campaign field in the template file.  For each failed record in a DI import, another dup Campaign record is created.

**Comment by judisohn** [comment]
More conversation on this, including a sample file to use to replicate the issue is found here: https://powerofus.force.com/0D58000002ySh7s 

When a record fails completely because the Contact had an error - so no Account, Contact or Donation is created - the Campaign is created. One a successful insert, the Campaign is created again.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000002xRJOAA2" target="_blank">W-011477</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.89 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.89
