### ISSUE TITLE
Lead Conversion incorrectly creates Household when not selected

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#2190]
Unclear what the correct behavior is, guessing it isn't this, 3.77. Should it always get a Bromer Household with a Salesforce.org Account, or just the Salesforce.org Account and Affiliation? 

Create Lead:
![screen shot 2016-07-29 at 4 44 48 pm](https://cloud.githubusercontent.com/assets/926530/17262848/cc2645a2-55ab-11e6-9d14-0fd27e103620.png)

Select 'Create new Account' during conversion:
![screen shot 2016-07-29 at 4 45 24 pm](https://cloud.githubusercontent.com/assets/926530/17262869/f4a577e6-55ab-11e6-84ae-99fc76f5a9a6.png)

Convert and note that the Salesforce.org Account was not created, and an Affiliation is created to the Bromer Household: 

![screen shot 2016-07-29 at 4 47 20 pm](https://cloud.githubusercontent.com/assets/926530/17262906/252d3322-55ac-11e6-9198-512b0d0283b6.png)

I would expect either:

1.  A Bromer Household, a Salesforce.org Account, and an Affiliation between Kevin and Salesforce.org OR
2.  No Household, and a direct connection and Affiliation to the Salesforce.org Account. 

#1 is probably the correct behavior IMHO...

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003ySygAAE" target="_blank">W-010932</a>

**Comment by judisohn** [comment]
Actually... this happened because your profile is set for Household as the Account default. Set it to Organization as the default (which is what we recommend and how the trial is configured) and you get Salesforce.org as the Account and Salesforce.org as the Affiliated Account, which is what you selected in the Conversion. To get option #1, you should select Account as 'Create Household Account.'

This is related to #1571 that I opened a while ago - Lead conversion gets funky when the Individual record type (HH or One2One) is the default.

**Comment by kbromer** [comment]
👍

Interesting - can we check for that? Might be as a easy a notification on the conversion page itself...

**Comment by judisohn** [comment]
Yeah, I hope so and I think it would be a good idea. That was the point of the issue I entered before. :-)

**Comment by davidhabib** [comment]
@kbromer @judisohn Since #1571 is open and is the proposed fix to this issue, should we close this one?
