### ISSUE TITLE
problem with languages on directions for new code contributors

### ISSUE THREAD

**Issue by lorenserfass** [SalesforceFoundation/Cumulus#2281]
Deployments fail using this set of directions.
http://developer.salesforce.org/Cumulus/Contributor/

Prior to deployment using ant, the translation workbench must be enabled manually, and several languages added (not sure about this list, but probably English, Spanish, French, German, and Japanese). If this is done, the ant deployment will work.

This issue was reproduced several times at the Boston community sprint.

**Comment by kbromer** [comment]
So interesting, I didn't have that issue at all, same thing (net new org, etc.), translation workbench is disabled.

**Comment by kbromer** [comment]
Ah, okay, i think we figured it out.  DeployCI (which the contributor tool also appears to use?) attempts the uninstall, including the translation files first.  If translation workbench is not enabled, the deploy will fail with an odd error around translations.  

The contributor instructions should be updated to reflect usage of deployDevOrg instead of deployCI, and, if necessary, the contributor tool should be updated to utilize deployDevOrg as well (and/or decide how to handle deployCI with the workbench off)

**Comment by kbromer** [comment]
Nope, nevermind, just that workbench and chatter need to be enabled. not too much we can do to resolve that dependency, other than document it in the setup prereqs
