### ISSUE TITLE
Hi, We are trying to run a batch in our Salesforce org, but the batch s failing and giving as exception as follows, NPSP: Too many DML Statements:151, this used to run perfectly in sandbox but after NPSP is updated, it is causing issue in sandbox too. We tried to debug the code using debug log but was unable to get the cause. Attaching the debug log..

### ISSUE THREAD

**Issue by abhimahajan50** [SalesforceFoundation/Cumulus#2305]
We already created a issue for this but it was closed without proper explanation and also I was unable to reopen the case #2303 
We are getting an NPSP error before the Finish() method of the batch and hence Finish() method is not executing.
Attaching the debug log file
[SF_DebugLog.txt](https://github.com/SalesforceFoundation/Cumulus/files/491071/SF_DebugLog.txt)

**Comment by judisohn** [comment]
@abhimahajan50 I closed the prior issue (as I will this one) because we don't offer customer or partner support here on Github. If you are not directly working with the developer who wrote this code for you, you can post this in the [Developers](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjxL) group in the Hub if you have access and perhaps someone can help you figure out strategies to avoid this error. For example, if too many records are being handled in a single batch.

Thanks for understanding!
