### ISSUE TITLE
Translation on picklist values make NPSP workflows & Triggers fail

### ISSUE THREAD

**Issue by gonzalos4g** [SalesforceFoundation/Cumulus#2333]
When translating Picklist values to Spanish in fields used by NPSP, the package stop functioning. 
Example Translating: npe03__Installment_Period__c, npe01__Preferred_Email__c, npe01__PreferredPhone__c.
Also translating Contact Roles make triggers not generating the Opportunity Contact Roles.
Also Relationships autocreation...
This is critical for Spanish Non-Profits, we have to find workarounds constantly. 
Please Fix.

**Comment by mpusto** [comment]
We are aware of these issues and have them documented here: https://powerofus.force.com/kA0800000004MOl
I would also recommend discussing with others in the Español group here:
https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000Coqi

There are various limitations from Salesforce.com which prevent us from changing some of these things, which is why we've documented them to alert our users.
