### ISSUE TITLE
first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_ContactTrigger: execution of AfterUpdate caused by: System.NoAccessException: Entity is not api accessible

### ISSUE THREAD

**Issue by jasonkelly** [SalesforceFoundation/Cumulus#2349]
Error Type: Batch Apex error
Error Date: 2016-11-04 03:10:08
Message: "First error: Update failed. First exception on row 0 with id 003A000000uVn8nIAC; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_ContactTrigger: execution of AfterUpdate caused by: System.NoAccessException: Entity is not api accessible Class...."

Context: npsp__RLLP_OppContactRollup_BATCH

Stack Trace:
null

--------------

The above error started appearing last week, around November 4, despite releasing no new Apex code around that time.

What is the best way to debug and fix the error? We are running the latest versions of both Declarative Lookup Rollup Summaries Tool and the Nonprofit Success Pack.

**Comment by judisohn** [comment]
Hi, [please see this post](https://powerofus.force.com/0D58000003345wn) on the Power of Us Hub which explains what is going on and a suggestion on how to resolve. If it doesn't help, please post in the Hub and we'll be able to get to the bottom of it. It's related to a change in error handling in the [NPSP 3.83 release](https://github.com/SalesforceFoundation/Cumulus/releases/tag/rel%2F3.83). We troubleshoot on the Hub, so I'll be closing this issue here.  Thanks for understanding!

**Comment by jasonkelly** [comment]
Thanks @judisohn. I've re-scheduled the jobs.
