### ISSUE TITLE
Clone button is Editing Current Level

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2356]
When a user clicks the Clone button with the Level override page set on Clone and then modifies the Level and Saves, the original Level is being saved and a new Level is not created.

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004Br1SAAS" target="_blank">W-016843</a>

**Comment by davidhabib** [comment]
When I put in comments that Clone was supported, i incorrectly assumed that the standard controller was receiving the cloned record as its current object, since that's how New works.  But turns out I was incorrect.  Overriding Clone just gives you the current object, and you have to then create the new object and use it instead.  We could easily add this support if we want to (~3-5 points).  So we should either add the support, or remove the Clone override on the template, and make sure documentation doesn't recommend setting the override.  @mpusto which do you want to do?

**Comment by judisohn** [comment]
@davidhabib Because the clone button was behaving incorrectly, I had already removed the override in the template after a brief chat with @mpusto yesterday. We can add it back later?

**Comment by davidhabib** [comment]
if we add the support in the visualforce page to do the right thing, then yes, we can add the override back.  We need @mpusto to decide if it is worth doing and to prioritize appropriately, or to close this as not supported.

**Comment by mpusto** [comment]
I think we'd like to do it, but it is not urgent since it's out of the template. And obviously the documentation should not recommend doing it.

**Comment by judisohn** [comment]
@davidhabib Is Clone set to override in the package? Because when I went to set it back to standard yesterday, I noticed that the default was the override. 

![image](https://cloud.githubusercontent.com/assets/4614343/20192173/bec79d00-a756-11e6-9cb4-c22f2615ace8.png)

**Comment by davidhabib** [comment]
yes, I just looked in the packaging org, and all three of the overrides (edit, delete, clone) are set for Levels.  I didn't think overrides ever got packaged!  But from your picture, you can see that in the subscriber's org, no override (use default) is not the same as standard salesforce.com page!  So we do need to change this in checked in metadata or add the support for it.  at least for now we are mostly covered given you've updated the Trial Template to no longer specify the override.

**Comment by judisohn** [comment]
@davidhabib Yes, that's what I thought. Thanks for confirming. And yes, it will only be an issue for those who install.

**Comment by jlantz** [comment]
Included in beta release 3.86 (Beta 3)
