### ISSUE TITLE
Daily NPSP error since npsp upgraded to 3.84 version in the sandbox.

### ISSUE THREAD

**Issue by pranoti-patil** [SalesforceFoundation/Cumulus#2367]
Hi,
 
The npsp sandbox org upgraded to 3.84 version on 10th November, 2016. Since then We start getting a rollup error every night.
 
I have attached an error screenshot.
 
Can anyone help me resolve this error?
 
Thanks.

![rollup bach error](https://cloud.githubusercontent.com/assets/23546509/20418580/17bf7a9e-ad75-11e6-9cb0-fcc96df70b2f.JPG)

**Comment by davidhabib** [comment]
It looks like one of your custom Opportunity Naming specifications is invalid.  You are now seeing this error that has existed all along, because NPSP recently improved our error reporting during batch operations, so they would not get lost.  Please post on the Hub if you are unable to resolve your issue, rather than entering issues in gitHub.  thanks.

**Comment by pranoti-patil** [comment]
@davidhabib Thanks for reverting.
We have logged this on hub on Monday. But we have not yet received any response.

**Comment by judisohn** [comment]
@pranoti-patil See [this post](https://powerofus.force.com/0D58000003345wn) please. Following the directions there should resolve this issue.
