### ISSUE TITLE
Salesforce.Common.ForceException: npsp.TDTM_Contact: System.LimitException: npsp:Too many query rows: 50001

### ISSUE THREAD

**Issue by TGMarcovecchio** [SalesforceFoundation/Cumulus#2381]
We have an external system using a .NET integration via SOAP to create and update records in a SF Instance  running NPSP 3.84.  The integration is updating / inserting contacts. The current contacts object has  74,798 records. Contacts carry an external id related to the integration (Personify Record Id). We are receiving the following message: 

2016-11-21 08:05:53.5056 ERROR SmeInterface.Job Failed to update contact '000011916878' Salesforce.Common.ForceException: npsp.TDTM_Contact: System.LimitException: npsp:Too many query rows: 50001

It appears the integration is attempting to update the contact with the associated Personify Id '000011916878'  and is somehow tripping a query limit in npsp.TDTM_Contact which I gather is a trigger leading to a trigger handler. This seems to be happening on a contact by contact update/insert basis for all contacts in the integration. 

Can you provide any insight into what might be causing this inside the npsp code? Is there a way to switch to- / use batch apex to avoid the query limit issue?

**Comment by davidhabib** [comment]
I'm afraid we can't debug this issue for you.  I'd look into how you have your org set up, and compare what happens when you insert a single contact in the UI vs. insert a single contact through your integration.  Things to consider are that when a new contact is inserted without an account, NPSP will automatically create an account for it, assuming your are using the One-to-One or Household Account model.  You should make sure that your integration profile has full permissions to the various account and contact fields, as well as any record types being used.  If you want to refer to our source code, its all here in gitHub at https://github.com/SalesforceFoundation/Cumulus/tree/dev/src/classes
