### ISSUE TITLE
MHUI: 'Auto Informal Greeting' checkbox often fails to save properly 

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#2418]
Seen in 3.87 (Beta 10) using Google Chrome

I was able to repro both using Selenium and by normal browser operation.

Note that on some occasions the save does happen correctly, but my experience is that more often the save fails in this way: 

The default state for the three checkboxes at the bottom of a MHUI page are to be checked. 

![screen shot 2016-12-14 at 9 39 25 am](https://cloud.githubusercontent.com/assets/204643/21191564/c73dce90-c1e2-11e6-9d1a-eb5a7b5865be.png)

(Note: save the URL for this page for easier navigation later)

Uncheck each of the three boxes and click Save

![screen shot 2016-12-14 at 9 39 30 am](https://cloud.githubusercontent.com/assets/204643/21191584/d9a8a9f6-c1e2-11e6-9be7-e16356236e8c.png)

Navigate back to the MHUI page using the URL you saved above. 

'Auto Informal Greeting' is (probably) checked even though you unchecked it in the previous step. 

![screen shot 2016-12-14 at 9 46 55 am](https://cloud.githubusercontent.com/assets/204643/21191638/08e43154-c1e3-11e6-8951-f89a9d1782d0.png)

**Comment by davidhabib** [comment]
@chrismcmahon  I'm guessing this is because even though you uncheck the box, you don't modify the names to not match the name format.  The code does work to detect that the name matches the format to enable the checkboxes.  this is for historical reasons where we had no support, and once we delivered the feature, we didn't want all old orgs to have to manually update their households.  So if you change your test to actually change the text to something different, I think you will then get consistency.  If that is not the case, reopen this issue with details.  thanks.

**Comment by chrismcmahon** [comment]
I'll try that, but as I noted in the original report, right now I sometimes see the state saved properly and often see the state saved improperly.
