### ISSUE TITLE
NPSP GAU rollups not working with "Use Fiscal Year" checkbox checked in NPSP setting

### ISSUE THREAD

**Issue by AnkurJaiswal619** [SalesforceFoundation/Cumulus#2440]
Hi,

We are facing issue when "Use Fiscal Year" is checked on NPSP settings.
NOTE: GAU renamed as "Fund Code" in our Org.

“Use Fiscal Year for Rollups” checkbox is selected as shown in screenshot below
![npsp_setting](https://cloud.githubusercontent.com/assets/21311075/21669204/d48dba02-d32f-11e6-86dc-423d1a30cec4.png)

We had created some reports and when we verified the numbers of these reports against the actual data that we are seeing on the “Fund” record, it seems the data is being credited in incorrect fields as highlighted in the screenshot below. The value from the current financial year is actually displayed in “Total Allocations Last Year” field and the value from last financial year is actually being shown in “Total Allocations Two Years Ago” field.

Snapshot of the report which indicates the total GAU calculation against a Fund Code for current Fiscal Year
(redacted)

Screenshot of Fund record depicting the incorrect fields in which the data is being updated
(redacted)

Snapshot of the report which indicates the total GAU calculation against a Fund Code for previous Financial Year
(redacted)

Screenshot of Fund record depicting the incorrect fields in which the data is being updated
(redacted)

Snapshot of the report which indicates the total GAU calculation against a Fund Code for current Calendar Year
(redacted)

Screenshot of Fund record depicting the correct fields in which the data is being updated
(redacted)

Please refer above screenshot and help us ASAP.

Thanks in Advance!

**Comment by judisohn** [comment]
**lurch: add

**Comment by judisohn** [comment]
Hi @AnkurJaiswal619 Thank you for the report and yes, I can confirm in some brief testing that you appear to be right. Fiscal Year rollups set in NPSP Settings do not seem to apply to GAUs. I have added this issue to the development team's backlog and I hope they'll be able to address it in an upcoming release. In the meantime, I would imagine you'll need to rely on reports to get the data you need, as there's nothing immediate you can do to change the way the rollups work. You'll need to wait for our team to update the code.

P.S. In the future, please report these issues in the [NPSP Group](https://powerofus.force.com/0F980000000CjRe) in the Power of Us Hub rather than posting directly here. Thanks!

**Comment by judisohn** [comment]
@AnkurJaiswal619 Now that I've independently replicated the issue, I edited your post to remove the screen shots as they had included your donors' information and this page is very public.

**Comment by judisohn** [comment]
@AnkurJaiswal619 Update - I ran my test incorrectly. I had neglected to select the Fiscal Year setting in GAU Allocation and only set it for broad rollups. When I corrected the setting and tested again, the rollups behaved correctly. So I'm going to close this issue as not reproducible. Please post in the NPSP Group in the Hub as I had previously suggested for further troubleshooting. Thanks!
