### ISSUE TITLE
1:1 account being created when an Account-Contact relationship was defined

### ISSUE THREAD

**Issue by brianpickett** [SalesforceFoundation/Cumulus#2471]
Steps to recreate:
1) Set the NPSP settings to the 1:1 account model and define a general record type for the 1:1 account. The presumption is this record type is used for more than the 1:1 account.
2) Create an Account using the same general record type
3) Create a Contact and in the Account name, populate it with your test account from step 2
RESULT: The contact is NOT connected to the Account as desired. Rather the contact is given a new 1:1 account.

**Comment by judisohn** [comment]
@brianpickett Thanks for reporting, but I believe this is by design as part of NPSP 3.87. See #2413 - We received a lot of requests for this. People were changing the account record type to/from the Household or 1:1 and getting frustrated that the account record did or did not automatically behave as a Household or 1:1 account. So our code now keeps the _SYSTEM: fields in sync with the expectation for the record type as an individual. With the 1:1 model, that means that the Account is set as the Primary Contact.

The presumption and best practice is that the record type set in NPSP Settings is only used for the selected account model. For non 1:1 accounts, you should have a separate record type such as Organization.

**Comment by brianpickett** [comment]
Thanks, Judi; I understand the logic. I suggest the help text surrounding the Account Model settings within NPSP settings be updated so its clear the record type selected for the Household or 1:1 model be solely dedicated to that use and none other.

**Comment by judisohn** [comment]
Great idea @brianpickett - @jvarese can you add a backlog story for this?
