### ISSUE TITLE
Engagement Plan: cannot create Dependent Task without Subject for main Task, etc.

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#2477]
This issue manifested itself approximately Jan 25 2017, sorry for the late report.

On the page at /apex/EP_ManageEPTemplate 

* Add an Engagement Plan Template Name
* Click Add Task
* Click Add Dependent Task. After seeing a spinner, Get error message "Error: You must enter a value" for Task Subject. 

It used to be possible to add a dependent task without a Subject for the task, that is no longer possible. 

![screen shot 2017-02-02 at 4 36 17 pm](https://cloud.githubusercontent.com/assets/204643/22573504/8183a0fe-e966-11e6-85e5-1ae157a90ea2.png)

Other things go haywire also when no Subject is present for things on this page: 

* Starting from scratch without entering Engagement Plan Template Name, click Add Task
* Nothing happens, page does not respond in any way. No errors in the web console.

* add an Engagement Plan Template Name
* Click Add Task
* Delete the text for Engagement Plan Template Name
* Add Dependent Task and Delete Task buttons respond but nothing happens in the page.

**Comment by judisohn** [comment]
@chrismcmahon I believe this is intentional behavior based on work done in #2334 (which you opened). It's intentional that you can't move on to the next task/action until the Task you're entering has a subject, as before you didn't get the error until you saved everything which wasn't desirable. There's a similar issue on Levels, I believe where things don't work right until the Name is populated.

**Comment by chrismcmahon** [comment]
Thanks Judi. I do like to report things here when behavior changes, just to be sure.
