### ISSUE TITLE
npsp.TDTM_RecurringDonation: execution of AfterUpdate caused by: System.TypeException: Cannot have more than 10 chunks ...

### ISSUE THREAD

**Issue by varonaRaposoSanchez** [SalesforceFoundation/Cumulus#2547]
Hi,

error on the subject appearing continously. How can we fix this?

Thanks in advance.

**Comment by judisohn** [comment]
Hi @varonaRaposoSanchez Please post this question in the [Power of Us Hub NPSP group](https://powerofus.force.com/0F980000000CjRe) along with more detail about your configuration and complete error message, and we'll try to help you get to the bottom of it. Github Issues are reserved for actionable items for the development team. If we find this is due to an addressable bug or issue, we can reopen. Thanks for understanding.
