### ISSUE TITLE
Editing Households Throws Error

### ISSUE THREAD

**Issue by tvanantwerp** [SalesforceFoundation/Cumulus#2553]
Have been unable to edit Households for the past two or three weeks. No changes to our settings. Page only shows the following error. Can provide more information for debugging on request--I'm not sure what other information would be of use. I don't have a lot to go on.

```
Unknown property '$ObjectType.Account.fields.npe01__One2OneContact__r'
Error is in expression '{!$ObjectType[sObjType].fields[field].dependentPicklist}' in component <apex:variable> in component npsp:util_formfield
Error evaluating dynamic reference 'npe01__One2OneContact__r.npe01__Secondary_Address_Type__c'
```

**Comment by judisohn** [comment]
Tom, you have Primary Contact > Secondary Address Type in your Manage Household Custom Field Set. Remove it and the error should resolve. I responded to your Hub post [here](https://powerofus.force.com/0D58000003KH0WD). In the future, you can just post on the Hub and if it turns out to be a bug or an issue for our developers to make changes, we can post here. Thanks!

**Comment by tvanantwerp** [comment]
Thanks, @judisohn! Sorry about posting here first--I never use the Hub but I'm on GitHub all the time, so it was just my first instinct.
