### ISSUE TITLE
Converting 1x1 account model to Household model in Salesforce NPSP 3.0

### ISSUE THREAD

**Issue by ramtinworld** [SalesforceFoundation/Cumulus#2560]
Hi,
We are trying to test the upgrade to NPSP 3.0 and change the account model to Household in our sandbox, however after running the utility listed here on this page none of the contacts gets converter.

https://powerofus.force.com/articles/Resource/NPSP-Convert-an-Existing-Account-Model-to-the-Household-Account-Model

The utility counts the batches and then it says e.g. 0 of 846 batches processed.

Is this a known issue and is it related to sandbox only?

Thanks

**Comment by judisohn** [comment]
@ramtinworld The conversion tool will only look at Contacts that have related Household custom object records. If the batch ran and there's no change, that's typically because there was nothing for it to do without the Household records. If that's not the case, please post a question in the [Upgrading to NPSP group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D5pE) in the Hub as we reserve Github issues only for actionable items for our development team. Thanks for understanding!
