### ISSUE TITLE
Contact Merge Error

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#257]
A user reported an error when trying to merge contacts with the NPSP Contact Merge functionality: 

https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D580000012clV3

I was able to reproduce the issue (although the error message is a little different), in the current (pre-Cumulus) codebase:

![screen shot 2014-01-21 at 10 45 01 am](https://f.cloud.github.com/assets/1894238/1968416/5ab1b15c-82e2-11e3-970a-5c60c52a73b7.png)

I was not able to reproduce it in the Cumulus codebase.

**Comment by JodieM** [comment]
Just in case someone googles to find this error again. It is indeed an error (apparently fixed in 3.x, but I have not verified that). 

It may be caused, as in my case, by Rollup Helper being the last "user" to edit a record (that's why there is much talk about Portal Users in conjunction to this error). Rollup Helper (or a portal user) is not a real user, so displaying the merge page can't display the user details and so fails. 

A quick workaround is to just edit both contact records so you are the user that has last modified each contact record and then it should work. Either that or upgrade to the latest version.
