### ISSUE TITLE
As a sysadmin, I want all of my existing Household__c data natively ported to the new Household Account model, including custom fields, so that my transition to the new model is as smooth as possible for my users. 

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#28]
- This is a large story and will need to be broken down into smaller stories
- Existing Household__c data including custom fields, should be transferred to mapped custom fields on the Account

**Comment by davidhabib** [comment]
** lurch: add

**Comment by mpusto** [comment]
It looks like a work item did not get created for this? I'm wondering if we should close as we will likely not invest time in this due to the amount of effort to check/create new fields to correspond to the old HH object, then re-map to the new or existing custom fields (and how could we be 100% sure unless we build an interface for people to map?). The amount of effort required to complete this feature and the number/percentage of customers it would impact is not large.

**Comment by davidhabib** [comment]
I think we could potentially copy all fields to the new account if the same developer name existed.  still would require the user to create these custom fields.  but I agree it is lower priority and likely not to get attention anytime soon.
