### ISSUE TITLE
Recurring Donations Automatically Being Created

### ISSUE THREAD

**Issue by Agroag** [SalesforceFoundation/Cumulus#2811]
Hi - We have a custom checkbox, sustainer, that is used on the Opportunity object. Checking that box creates a recurring donation for that opportunity (It's backwards). The issue is, over time, more and more recurring donations are created (some with, some without opportunities). Also, instead of creating new opportunities each time a credit card is charged, it is adding transactions to one opportunity, which is incorrect.

We also have a large amount of DLRS fields.  If one of these roll ups edits a recurring donation, what are the effects from NPSP? 

Thanks.

**Comment by judisohn** [comment]
Hi @Agroag - as with the other issue you posted, this is best for the Power of Us Hub where the community can help you troubleshoot solutions. This isn't related to NPSP, so I would probably post in the [System Administrators group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CkCM) for best results (since it's your customization and DLRS)

As I mentioned in the other thread, we reserve Github issues for items that have been verified as bugs/issue in the code for our developers to address, and not for general troubleshooting. Thanks!
