### ISSUE TITLE
cci to create scratch org - error on Windows

### ISSUE THREAD

**Issue by daveb-501commons** [SalesforceFoundation/Cumulus#2819]
I'm watching https://www.youtube.com/watch?v=3NDouZ3-LFE

and mentions after you get cci installed you can do the following
1) git clone https://github.com/SalesforceFoundation/Cumulus
2) cci org scratch dev scratch --default

but I get an error on Windows 10 saying can't find module anydbm.

**Comment by jlantz** [comment]
Hi @daveb-501commons since this appears to be an issue with CumulusCI running on Windows rather than with the NPSP repo itself, could you file this issue in the CumulusCI repository at https://github.com/SalesforceFoundation/CumulusCI where my team that works on our tooling more actively monitors issues?

We should be able to take a look today and get you some resolution.  I'll go ahead and close this issue and we can pick up any additional conversation in the CumulusCI repository.

**Comment by jlantz** [comment]
Oops, just saw you did already open an issue in CumulusCI.  Thanks!
https://github.com/SalesforceFoundation/CumulusCI/issues/491
