### ISSUE TITLE
Updating Opportunity Primary Contact to a Contact already receiving a Contact Role updates Contact Role to correct Contact and Role Name, but does not check 'Primary'

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/Cumulus#2894]
With fresh NPSP 3.117 and default NPSP Contact Role settings:

1. Create an Opportunity from a Contact ("John Smith") using NPSP New Contact Donation button.  The new Opp receives a Contact Role record where John Smith is Contact, Primary = TRUE, Role = Donor, as expected.

2. Click New button on Contact Role to add a new CR record.  Choose a different Contact ("Jane Doe"), Role = "Influencer", Primary = FALSE.  Now there are 2 CR records - John is primary, Jane is not.

3. Update the value of the Primary Contact field on Opportunity to "Jane Doe".

Issue: John's CR record is deleted and Jane's CR record is not set to Primary=TRUE, leaving the Opp with no Primary CR records.  I believe that setting Primary Contact on Opportunity should never leave the Opp with no primary CR records.

Note: It doesn't matter whether Jane is in the same or a different HH Account than John.

**Comment by judisohn** [comment]
Thanks @johnfine - I did some testing and confirmed this behavior. I updated the title to better reflect exactly what is going on. It only happens if the Contact who is now the primary is already a Contact Role on the Opportunity. If the Contact is changed to another Contact who is not already associated with the Opportunity, the OCR updates correctly, including the Primary checkbox.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000097HxlAAE" target="_blank">W-021728</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.131 (Beta 11)

**Comment by mrbelvedere** [comment]
Included in production release 3.131
