### ISSUE TITLE
Is it possible to install with SFDX in a scratch org

### ISSUE THREAD

**Issue by keithmancuso** [SalesforceFoundation/Cumulus#2949]
We have started workign with SFDX and are really enjoying it but its frustrating that there seems to be no supported way of installing NPSP in a scratch org.

Is there a timeline for something like this or better yet a workaround to use in the meantime?

**Comment by jlantz** [comment]
You can definitely install NPSP into a scratch org, we do it every day in development and in our automated builds.  The challenge is that NPSP requires a fair amount of dependencies such as record types on Account and Opportunities and the current versions of the 5 underlying managed packages.  Here's the build output from one of our automated builds that completely automates creating a scratch org, installing all dependencies, deploying NPSP unmanaged code from a feature branch, running Apex tests, the deleting the scratch org (we run this build on every commit our the Cumulus repo):
https://mrbelvedereci.herokuapp.com/builds/16913/flows

To handle that, we build and maintain CumulusCI, an open source framework for portable automation in Salesforce projects which integrates with SFDX and handles the dependency requirements for our projects.  With CumulusCI properly configured and SFDX connected to your devhub, you should be able to get NPSP into a fresh scratch org with the following commands:

**For Unmanaged NPSP**
`cci flow run dev_org --org dev`

**For Managed NPSP**
`cci flow run install_prod --org dev`

The setup instructions for CumulusCI are located here:
http://cumulusci.readthedocs.io/en/latest/tutorial.html

One other cool thing to note about CumulusCI for NPSP... If you want to manage your project on top of NPSP inside a Github repository, you can configure CumulusCI to automatically inherit your project's dependencies directly from the NPSP Github repository (aka Cumulus) by just including the url to the github repo as a dependency:
http://cumulusci.readthedocs.io/en/latest/features.html#case-study-salesforcefoundation-cumulus

The challenge is that SFDX only allows you to install a managed package version using the PackageVersionId which must be obtained from the packaging org for the package.  We intentionally don't publish the PackageVersionId for the underlying packages to avoid the risk of someone accidentally installing one of the 3.x versions of the packages individually which would break an NPSP 2.x org until the full upgrade to NPSP 3 was completed in the org.

You can also use https://mrbelvedere.salesforcefoundation.org/mpinstaller/npsp to install NPSP into a scratch org through the web.  Just use the Sandbox option since scratch orgs run on sandbox pods.

We have a Salesforce.org DevOps Tooling group in the Power of Us Hub which is a great place to get help with using our tooling.

**Comment by keithmancuso** [comment]
Super helpful information, thanks!
