### ISSUE TITLE
NPSP Data Import Capped at 50,000 Records in UI

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3047]
When you hit the "Start Data Import" button (and presumably the "Process Batch" button in the NPSP Data Import Batch object), the configuration screen will not load if there are more than 50,000 records to import. 

While the BDI engine itself can process more than 50,000 records because we are batching the data, the BDI_DataImport Visualforce page errors out because the crecToProcess variable (used to display the number of records to be processed) does a SOQL query with a count() to display the total records to import (Lines 347-354 in BDI_DataImport_CTRL). 

```
crecToProcess = [select count() from DataImport__c where Status__c <> :BDI_DataImport_API.bdiImported and
            NPSP_Data_Import_Batch__c = :diBatch.Id];
```

**Error displayed to user:**
![bdi config error](https://user-images.githubusercontent.com/29731456/38961037-b3e184ac-4334-11e8-86b4-cd4f4cfb314b.jpg)

**Steps to Reproduce:**
1. Import over 50,000 records to the NPSP Data Import object
2. Hit the Start Data Import button.

Acceptance Criteria should include testing around NPSP Data Import Batch processing as well.

**Comment by jesslopez-sf** [comment]
Linked to [W-024093](https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x8000000AVZsUAAX/view)

**Comment by njjc** [comment]
Thanks for reporting, @jesslopez-sf. I believe this can easily be fixed with a LIMIT 50000 at the end of the query. That being said, it [looks like aggregate queries won't count against governor limits in Summer '18](https://twitter.com/fishofprey/status/986358576171048960?s=11), so it would likely make sense to remove that limit once summer '18 hits. Do you think it's worth fixing in the meantime? The workaround is manually kicking off the batch process from anonymous apex.

**Comment by davidhabib** [comment]
I don't believe the LIMIT statement works on aggregate queries as you might expect, since LIMIT just affects the number of rows returned.  computing the aggregate count will still hit errors I believe.

**Comment by force2b** [comment]
That's correct - LIMIT cannot be used an aggregate query; however `SELECT count()` by itself doesn't count as an aggregate query, so adding a limit would work. The only change I'd recommend to that is to get the actual number of available query rows using `Limits.getLimitQueryRows() - Limits.getQueryRows()` (maybe subtracting some additional value to cover future queries in the transaction) rather than hardcode 50000.

Also, I'm fairly sure I heard at TDX that `SELECT count()` was going to be updated (at some near point in the future) to only use up a single query row. #SafeHarbor of course.

**Comment by njjc** [comment]
Why are we doing it everywhere in Health Check then? Doesn't limiting the query to 50k mean we won't hit the 50k query row limit, regardless of aggregation? @davidhabib

**Comment by davidhabib** [comment]
You are right Nic.  I guess I forgot!  Here's the doc:

You can use LIMIT with count() as the fieldList to count up to the maximum specified.

You can't use a LIMIT clause in a query that uses an aggregate function, but does not use a GROUP BY clause. For example, the following query is invalid:

**Comment by jesslopez-sf** [comment]
FYI -- I just confirmed in a Summer '18 org that this is no longer an issue thanks to the new limit changes on COUNT().

**Comment by force2b** [comment]
Does this just work without any changes or is it necessary to up the API Version of the apex class to 42 or 43?

**Comment by jesslopez-sf** [comment]
@force2b -  It works without any changes.

**Comment by jesslopez-sf** [comment]
The config page actually opens now and shows that I have more than 50K records:

![npsp data imports 50k](https://user-images.githubusercontent.com/29731456/40740220-3ec94008-6416-11e8-88bb-1c07dec22731.jpg)
