### ISSUE TITLE
Classic NPSP app not visible in Lightning Experience

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#3208]
The legacy Nonprofit Success Pack app included in the NPSP package does not have the 'Show in Lightning Experience' box checked within the package. Until recently, admins could manually edit the App and check the box to use the existing App in Lightning Experience. Now, the checkbox is not editable to package subscribers.

![image](https://user-images.githubusercontent.com/4614343/40543597-1c7364e2-5ff3-11e8-808e-777eb29b8a09.png)

Until we can update the package, the easiest and best workaround is to follow directions [here](https://powerofus.force.com/articles/Resource/Get-the-NPSP-Trial-Experience-with-Lightning-Apps?navBack=H4sIAAAAAAAAAIuuVipWslLyzssvz0lNSU_1yM9NVdJRygaKFSSmp4ZkluSA-KVAvn58aaZ-NkyhPpCDqqs2FgCHRwp0TQAAAA&popup=false) to create a new Lightning App. This App would not be impacted by any future packaging changes and will be able to take full advantage of all the extra App features available only for Lightning Apps.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AXVfjAAH" target="_blank">W-025064</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.131 (Beta 4)

**Comment by sarahjaytt** [comment]
Classic NPSP app stopped being visible for me in Lightning experience last week. I am 1 of 2 system admins for my company and I was the only user affected. SF tech support identified this as a bug and gave me a workaround to create a new NPSP app in App Manager. That crashed the system for the other system admin so I removed and we'll be using Classic until bug is fixed. Frustrated.

**Comment by netimpactmaythefourth** [comment]
This is impacting me too; I created a sandbox I went in to use and there's no NPSP app visible in Lightning. I agree with Sarah that this is a frustrating bummer.

**Comment by force2b** [comment]
There is a post for this in the Power of Us Hub: https://powerofus.force.com/0D58000004GV0Vq

**Comment by coriobriensfdo** [comment]
This is a known issue due to a change in how end user organizations can edit a managed classic package: https://github.com/SalesforceFoundation/Cumulus/issues/3208

We will update the source package to check the box to make the app visible in Lightning, but due to the impending release of Summer '18 where we'll skip a push release, it won't be deployed to Production until the end of June.

In the meantime, you can quickly and easily create a Lightning App with the same tabs (or tabs of your choice) and then you won't have to worry about unexpected packaging changes again and you'll be able to take advantage all the additional features a true Lightning App has to offer. 

https://powerofus.force.com/articles/Resource/Get-the-NPSP-Trial-Experience-with-Lightning-Apps

**Comment by mrbelvedere** [comment]
Included in production release 3.131
