### ISSUE TITLE
Household Opportunity Contact Role calc fails with 100K record non-selective query error

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#326]
_Issue by **[dmcheng](https://github.com/dmcheng)** from Tuesday Oct 29, 2013 at 20:39 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Households/issues/39_

----

If Enable Household Opportunity Contact Role is enabled and there are over 100K household records, then Opportunity insertion fails with a non-selective query error.

"npo02.Household_Opportunity: execution of AfterInsert caused by: System.QueryException: Non-selective query against large object type (more than 100000 rows). Consider an indexed filter or contact salesforce.com about custom indexing"

The opp insert fails both in data loader and in the UI (adding an opp from a contact detail screen).

**Comment by kbromer** [comment]
**lurch: attach W-007370

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZtAAI" target="_blank">W-007370</a>

**Comment by davidhabib** [comment]
OK, I've tested in our large LDV org (which has over 100k opps), and there are no errors creating an additional opp on a large household.  But I realize that this bug was reported against NPSP 2, so it was assuming the 1x1 model with Household objects.  I have looked at the NPSP 2 code, and see it is similar to our NPSP 3 code (no surprise). the code paths for HH Account vs HH Object are the same in this code. The selects just look for household__c in :listHHId or Acount in :listHHId. looking at the query plan for all the queries in this trigger handler haven't found any issues. So I'm personally OK if we decide to just close this without setting up an LDV org with Household Objects and 1x1 model, if we feel it is not high priority enough to validate/test/fix.
