### ISSUE TITLE
Household OCR Excluded Record Types list is missing in NPSP Settings

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#3332]
The list of record types to exclude when auto-creating household member OCR records is missing in NPSP Settings (Donations -> Contact Roles -> Edit).

![image](https://user-images.githubusercontent.com/801017/41659937-98e09480-7468-11e8-8cac-80dd0b185df0.png)

**Comment by force2b** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBDbAAP" target="_blank">W-025766</a>

**Comment by julieloyd** [comment]
I'm seeing this issue too, but only if Customizable Rollups are enabled. The Soft Credit section under Contact Roles in Settings is also completely missing. If you disable the rollups, then the Soft Credit section reappears. In this state, Donor Statistics settings also disappear. Not sure if I should log any of this as a separate issue, or if the same.

**Comment by force2b** [comment]
Those are actually all valid. Once Customizable Rollups are enabled, some of the rollups related settings in NPSP settings are hidden. This is covered in the documentation. What's missing here are the list of Record Types to exclude when creating OCR records for Household Members. That's not specifically a rollup setting and so it should be visible whether Customizable Rollups is enabled or not.

**Comment by judisohn** [comment]
@julieloyd That is completely normal and expected behavior and I believe it might be in the documentation as well. All of the soft credit rollup values, donor statistics, etc. are incorporated into Customizable Rollups and are therefore not used/hidden. However, the Household OCR Contact Record Type ID setting is not affected or changed by Customizable Rollups and shouldn't have been hidden with the rest. Hope that helps!

**Comment by julieloyd** [comment]
Well, I feel sheepish. I broke my own cardinal rule - always check the documentation. Thanks for the quick response!

**Comment by judisohn** [comment]
@force2b Wait. @bethbrains and I think this is actually WAD.

I checked my QA org and I see the same as you (sorry, should have checked first) *but* that's fine because the org doesn't have any Contact Record Types defined. When I look at an org that does have Contact Record Types, I see this which is correct. 

![image](https://user-images.githubusercontent.com/4614343/41737364-14a584dc-755d-11e8-9a3f-6136cd1938ea.png)

![image](https://user-images.githubusercontent.com/4614343/41737377-1c8d5274-755d-11e8-950c-4bf77084ce0e.png)

Can you (or @julieloyd) clarify what you're expecting to be different? I thought your screen shot was from pre-CLRP and the entire section was missing, but that doesn't appear to be the case. Thanks.

**Comment by force2b** [comment]
You're correct @judisohn. That specific list of record types is actually a list of Contact Record Types,  so if there are no Contact Record Types in the org the list will be empty. I'll close this.
