### ISSUE TITLE
Preferred Phone field not updating phone numbers on edit

### ISSUE THREAD

**Issue by mrchev** [SalesforceFoundation/Cumulus#3430]
Hi all,

Found this in my org when editing the preferred phone number.  If you edit a contact record with no phone numbers listed and change the Preferred Phone type to a new value and enter the number in the "Phone" field, upon save the value is "Phone" is wiped out and the number doesn't populate the corresponding number field based on the Preferred selection.

Sample before:

![preferred change from home to mobile](https://user-images.githubusercontent.com/41024163/42472404-2ccc2ab2-838f-11e8-8633-6ecc35652b4d.png)

Sample After: 

![post save](https://user-images.githubusercontent.com/41024163/42472419-3605aed2-838f-11e8-8211-72e6766f79ad.png)

Adding the phone number to the designated field, "Mobile" in this case, works just fine.  Users are going to hit the 1st field though, and won't think to check that the phone number saved.  Is this a known issue, or I am doing something silly?

**Comment by judisohn** [comment]
Hi @mrchev Please do me a favor and post in the [NPSP Group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe) in the Hub. That's where we do all our support/troubleshooting and if this turns out to be a replicable issue, we can always reopen for the developers here. Thanks!
