### ISSUE TITLE
Customizable Rollups: Unexpected Filtering Results

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3854]
It seems that the **_Account: Total Number of Gifts_** rollup has some bearing on other rollups. If I hook that rollup up to a Filter Group where anything with an Opportunity Type of “New Customer” is filtered out (Not in List or Not Equals), the rollup works as expected (it only counts Opportunities that meet the criteria). If I modify the **_Account: Total Gifts_** rollup so that there is no Filter Group, it is not rolling up the Opportunity. It almost seems like it's taking the other rollup's Filter Group into consideration. There are no errors in the Error Log.

**Screenshot of Opps Won:HC Filter Group:**
![filter group](https://user-images.githubusercontent.com/29731456/49456845-c9b5a280-f7b7-11e8-8e44-05bfc0e80d3b.png)

**_Steps to Repeat:_**

1. Create a Contact (First Name = Debbie; Last Name = Donor)

2. Enable Customizable Rollups in NPSP Settings → Donations --> Customizable Rollups

3. Configure Customizable Rollups and click on Filter Groups.

4. Modify the **Opps:Won (HC)** Filter Group so you have an additional Filter Rule:
    A. Object = Opportunity
    B. Field = Opportunity Type
    C. Operator: Not in List
    D. Value = New Customer

4. Go back to Customizable Rollups and make the following changes
    A. Account: Total Gifts — Change Filter Group to “No Filter Group (Include All Records)”
    B. Account: Total Number of Gifts - Verify that Filter Group = Opps:Won (HC)

5. Create an Opportunity (Name = Issue 1, Account Name = Donor Household, Amount = 1000, Close Date = today, Opportunity Type = New Customer, Stage = Closed Won)
Go to the Donor Household Account record. The Total Gifts field should be $1000, but it's showing $0. The Total Number of Gifts field is correct at 0, since the Filter Group should have filtered this Opportunity out. Hitting the Recalculate Rollups button does not resolve the issue.

6. Create a second Opportunity without an Opportunity Type (Name = Issue 2, Account Name = Donor Household, Amount = 500, Close Date = today,  Stage = Closed Won)
Go to the Donor Household Account record. The Total Gifts field should be $1500, but it's showing $500. The Total Number of Gifts field is correct at 1, since the Filter Group should have filtered the first Opportunity out. Hitting the Recalculate Rollups button does not resolve the issue.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQ1yQAE" target="_blank">W-030179</a>

**Comment by shawnholt** [comment]
HI @jesslopez-sf - Experiencing possibly related issue in this use case and not sure if it is this bug, a different bug or behavior design.

- On account we created several fields to support dual memberships (e.g. Membershi_2_Amount).
- On membership record type opportunities there is a picklist field called "program" to determine if it should apply to the Membership 2 fields.
- Created a new filter group (e.g. Membership 2) to only include opportunities where program = "Membership 2"
- For initial migration, we added values to Membershi_2_Amount.

**The expected behavior:**

- Only update the account fields when field filter is passed  (e.g. only update Membershi_2_Amount field on an account where related opportunity program = "Membership 2").

**Actual behavior**

- On an account where any field rollup passes the filter, (eg. total gifts) all target rollup fields are  overwritten even when a specific field filter group (e.g. Membership 2 ) fails.

**Use Case Impact**

- When migrating legacy data it is often useful to put values in the target of roll ups unless a new opportunity record is created that passes the field filter.  

- For example, migrating years of legacy  membership data, we can keep the join, end, level, status, etc in the target rollup and then when a new opportunity arrives, it will "take-over" and update the target fields using customized rollup filter logic.

- The alternative is to create dummy membership records, additional triggers, fields, formulas, etc. as a work-around.

**Comment by coriobriensfdo** [comment]
@shawnholt We don't support the NPSP here in GitHub, and generally will want to vet something is an actual bug in a separate org before we include it in GitHub Issues. 

Instead, can you place all this (great) detail in a post in the Hub? I'd recommend the [NPSP Group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe). If it is indeed a new aspect of the bug, we'll make sure the developers see that ensure the upcoming fix will resolve it.

**Comment by mrbelvedere** [comment]
Included in beta release 3.145 (Beta 15)

**Comment by mrbelvedere** [comment]
Included in production release 3.145
