### ISSUE TITLE
Limited to the number of Opp. record types to exclude from Payment records auto-creating

### ISSUE THREAD

**Issue by paulbfischer** [SalesforceFoundation/Cumulus#4122]
Please see error message. 

<img width="1440" alt="Screen Shot 2019-03-14 at 1 37 24 PM" src="https://user-images.githubusercontent.com/4922633/54384505-c493a980-466a-11e9-8bc7-e406a04c0eb1.png">

**Comment by coriobriensfdo** [comment]
Hi @paulbfischer, we don't typically support our products here in GitHub. Instead, can you please post this in the Power of Us Hub, in the [Nonprofit Success Pack group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe)? The community can help troubleshoot the problem, and if it does turn out to be a repeatable bug, we can create an issue to log it in our backlog. 

Thanks!

**Comment by coriobriensfdo** [comment]
@paulbfischer Just found your post (and David's reply) in the Hub. https://powerofus.force.com/0D51E00004kVhC2

We need quite a bit more information to properly log an Issue (exact steps to repeat, etc.) and to first prove that it happens in an independant org rather than just your org. I'll do some investigation and create a new issue to log it if we can repeat.

**Comment by coriobriensfdo** [comment]
@paulbfischer Unfortunately the limit of 255 characters is the max allowed therefore cannot be modified at this time. Please consider reducing the size of each Record Type name, or the number of record types in your org to fit the limit. 

Hub threads
https://powerofus.force.com/0D51E00004kVhC2
https://powerofus.force.com/0D58000004WGESU
