### ISSUE TITLE
Rollup doubles if there are two opportunity contact roles to the same contact

### ISSUE THREAD

**Issue by danhowellnz** [SalesforceFoundation/Cumulus#4132]
We had an opportunity with the same contact added to an opportunity twice.

The opportunity amount was $25,000. The total gift amounts on the Contact was $50,000.

Can you exclude the second contact in the roll ups? As you cannot add a trigger to stop duplicates being added.

**Comment by coriobriensfdo** [comment]
@danhowellnz we don't provide product support here in GitHub. Can you please post in the [NPSP Group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe) in the Hub?

**Comment by danhowellnz** [comment]
It's not support. It's a bug in the roll up tool. We have resolved it in our own org. 

This should be added as an issue

**Comment by coriobriensfdo** [comment]
@danhowellnz before something can be logged as an issue in GitHub, we need the exact steps to reproduce it in an independant org. Often what seems like a bug is due to the setup of NPSP, or configuration of the rollups, soft credits, etc. 

If you wouldn't mind taking a few mins, it would be really great if you can post your issue, steps to reproduce it, and how exactly you solved it in the Hub group I mentioned above. Then, if we can repro it in another org (our own test orgs), I can either re-open this Issue or create a new one.  

I apologize for any inconvenience that may cause you, but it's how we are able to maintain a clearly defined list of actual bugs here in GitHub rather than issues affecting only a particular customer or due to setup issue.

**Comment by danhowellnz** [comment]
Understood and agreed. Will do.
