### ISSUE TITLE
Data Import update fails:  (Data Import ID) 

### ISSUE THREAD

**Issue by anuradha-source** [SalesforceFoundation/Cumulus#4196]
I'm trying to update couple of contacts. My contact1 and contact2 import ids are mapped.

Contact2 Imported
0031U00000McZZ2QAN

Contact1 Imported
0031U00000McZZ1QAN

After mapping, click on Next, and it throws below error:

The matching field you chose (Data Import ID) is not mapped and is required for an Update and Insert operation.

Any help is appreciated. thanks.

**Comment by judisohn** [comment]
Hi @anuradha-source We do not provide direct support here in Github. Instead please [post in the Power of Us Hub](https://powerofus.force.com) and be sure to include the Nonprofit Success Pack topic tag.

The problem you are facing is due to incorrect configuration in the Data Import Wizard. Please review the section in the [data import workbook](https://powerofus.force.com/s/article/NPSP-Administrators-Guide-to-Importing-Donor-Data) and be sure you're not selecting to match to anything and instead you're selecting 'Salesforce.com ID' for the appropriate fields (Contact1 Imported and Contact2 Imported). That should resolve your issue.
