### ISSUE TITLE
Merge tool does not merge household

### ISSUE THREAD

**Issue by adplatonov** [SalesforceFoundation/Cumulus#4345]
Lets suppose:

Contact 1 on HH account 1
Contact 2 on HH account 1

Contact 3 on HH account 2

Then, if I merge both Contact 1 and Contact 2 into Contact 3
HH account 1 is not merged into HH account 2, but renamed into anonymous.

**Comment by judisohn** [comment]
Hi @adplatonov - This behavior is expected if you are either not using the NPSP Contact Merge tab or do not have the NPSP Delete button overridden correctly. We intentionally do not delete empty Accounts since it might also delete other connected objects. 

Please post any follow up questions on the [Power of Us Hub](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack) as we don't provide support here on Github. Thanks!
