### ISSUE TITLE
NPSP Contact Merge tool does not merge empty households

### ISSUE THREAD

**Issue by adplatonov** [SalesforceFoundation/Cumulus#4354]
Steps to reproduce:

Setup:
Contact 1 on HH account A
Contact 2 on HH account A
Contact 3 on HH account B

Case 1:
merge Contact 3 into Contact 2

result:
HH account B is merged into HH account A

Case 2:
merge both Contact 1 and Contact 2 into Contact 3:

result:
HH account A is not merged into HH account B, but renamed into anonymous.

**Comment by judisohn** [comment]
Refer to comment on #4345

**Comment by adplatonov** [comment]
Hey @judisohn Why does this one closed? The bug is right here https://github.com/SalesforceFoundation/Cumulus/blob/8b9f91fc1bb72b01812652a7729a8b51eb047f47/src/classes/CON_ContactMerge.cls#L138

**Comment by judisohn** [comment]
@adplatonov Because the behavior you're describing is as intended if you're not using the NPSP Contact Merge tab with the Contact Delete button set to override to the NPSP override Visualforce page. The code you're referencing is only called if you're using the Contact Merge tab. I just did a test with the same criteria you outlined with the merge tab, and no Anonymous Household was left behind.

You will, however, get an Anonymous Household if you use a 3rd party contact merge tool or the built-in Lightning component.

If you're getting this behavior despite using the Contact Merge tab and the override is on, then please open a support ticket or post in the Hub. Thanks!
