### ISSUE TITLE
BUG: contact's phone overwritten with account phone when an Account is created before the Contact

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#542]
Thomas Taylor (CRM Science)
Huh - hadn't run into this before, but can confirm that it exists, both in the current version and in Cumulus Beta. 
I reproduced it as follows:
1. Create an Account with a phone number
2. Create a new Contact (via Contact Tab > New) and select that Account through the Account lookup.
3. Fill one phone number field on the Contact. Select the corresponding value in Preferred Phone picklist.
4. Save record.
Result - Account's phone number appears in whichever phone field was filled out on the contact, as well as Contact.Phone. Phone number that was entered on the Contact has disappeared. Note that this happens with ANY appropriate combination of Preferred Phone and entered phone field.

@Cumulus App - Beta Feedback
Like
   ·   Today at 6:22 PM
Thomas Taylor (CRM Science)
Thomas Taylor (CRM Science)
Adding - it's a conflict between the phone workflows and the standard behavior of copying the Account.Phone and Account.Fax to the Contact on save in this data entry scenario.

**Comment by judisohn** [comment]
I've confirmed this indeed happens as @tet3 describes. Unfortunately, as he says, it's due to the standard Salesforce platform behavior which is copying the account's phone number to the contact well before any workflow rule can fire. 

Only way to get a different phone number at time of entry is to expose the standard Phone field on contact so the user can see that it is auto-filling and can overwrite it, or use a custom phone field on account. Or we can try and edit the Contact.PhoneChanged_(value) workflow rules to anticipate this and work around it. 

This only happens with contacts directly associated to accounts. Workaround is to edit/disable workflow rules or use standard Phone/Email fields.
