### ISSUE TITLE
Bug: Lead Conversion doesn't create household record (unless being merged into an existing contact).

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#685]
Daniel Trimble (KIDANGO INC)
 
Bug with #NPSP Lead Conversion?

The NPSF lead conversion intervention process worked pretty well, but there seems to be a glaring bug. Am I the only one who's experiencing this?

1. Created a new lead. "George Washington", with a Company of "Self"
2. From lead record, clicked Convert
-----> NPSF conversion process, specified to create a new contact, not create an opportunity, and not email the owner
-----> NPSF converted the lead to a contact with his own individual account. It did NOT create a household.
3. From lead record, created a new lead. "Mr. George Washington", with a Company of "Self"
4. From lead record, clicked Convert
-----> NPSF conversion process, specified to merge with the existing George Washington contact, not create an opportunity, and not email the owner
-----> NPSF merged the lead data correctly. And this time it DID create the household

It seems the lead conversion process only creates the household record if it's merging the lead into an existing contact. Otherwise, I have to manually create the household.

**Comment by davidhabib** [comment]
@judisohn @kbromer I see that Kevin's comments imply we will do what bhaplern suggests, but I think that conflicts with a major use case.  In npsp 2.0, and now with a fix I've got ready for 3.0, if the company specified in the lead isn't one of the special ones (self, individual, name, empty), we just redirect to the standard Salesforce LeadConvert page.  So that fix would prevent doing what bhalpern suggests. 

So we can't have it both ways.  Either we defer to standard LeadConvert when the company isn't special, or we always go through our lead convert, and always create the individual account (bucket, 1:1, or household) and set the primary affiliation to the company account we create.

Thoughts?

**Comment by judisohn** [comment]
@davidhabib Right, I see what you mean. I can picture having a separate custom field on Lead that would track 'Employer' as our model is to have the standard field that's matched to Account be the Household and a custom field that matches to the company/employer. The challenge, even if we didn't defer to standard LeadConvert, is that we would then need to match a custom text field on Lead to an Account in order to populate a Primary Affiliation field even after standard conversion.

**Comment by bhalpern** [comment]
@judisohn I think that sounds about right. @davidhabib If I understand correctly I don't see the benefit of standard LeadConvert functionality wise so if it can't be used I wouldn't sweat it. 

My thought is that Leads should perfectly match Contacts. They should have the same fields, in the same places, used for the same purposes. Conversion should simply create a new Contact from the Lead, transferring all of the Lead's information and running any scripts (including account creation, based on Household/bucket/1:1 setting). I'm not sure how best to grandfather in existing leads for the transition, but that shouldn't be terribly difficult to figure out. Point being: this is what I would envision from a rewrite... Plain and simple: Leads look like Contacts in every way so the conversion is a piece of cake! Hope it helps!

**Comment by judisohn** [comment]
@bhalpern Right, but keep in mind that matching text to relationship fields requires an interface for a user to make a decision. Automation never goes smoothly here. Think about how standard Lead conversion works - If you have an Account called Salesforce and another account called Salesforce  Foundation, and the person puts SFDC or Salesforce.com in the text field, which account should be selected? In the standard conversion you get code's best guess as to what could match and the user selects the right choice.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.40 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.40
