### ISSUE TITLE
BUG: permissions issue on npsp__Schedulable__c

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#859]
Seems like the Cumulus LMA user doesn't have the right permissions on the object. We need to investigate whether we can give it the right permissions, or whether we have to remove the scheduling of the job from the install script and let it get scheduled when the user visits the settings page.

Sample error:

----------------------

Subject: Developer script exception from KELL Partners : 'NPSP Global Scheduler' : sObject type 'npsp__Schedulable__c' is not supported.
Apex script unhandled exception by user/organization: 005d0000003HZDc/
00Dd0000000gQd0

Scheduled job 'NPSP Global Scheduler' threw unhandled exception.

caused by: System.QueryException: sObject type 'npsp__Schedulable__c' is not supported.

Class.npsp.UTIL_GlobalSchedulable.execute: line 44, column 1

**Comment by ceiroa** [comment]
We are still getting a large number of errors of this type. The thing is that the 'NPSP Global Scheduler' job should not be scheduled at all. If I remember correctly (we need to do more research - it's possible I'm mixing issues), there was an issue (could not be resolved - platform limitation) around the install script not being able to query certain objects. That forced us to replace the 'NPSP Global Scheduler' with 3 instances of 'Master Schedulable'. In addition to scheduling the instances of the new version, the install script should be aborting the old one. It doesn't seem like the abort is working.

**Comment by judisohn** [comment]
@ceiroa doing some clean up for Lurch - do you know if this is still an issue?

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fs3AAA" target="_blank">W-008269</a>

**Comment by ceiroa** [comment]
We looked at a number or orgs, and they are either in a Beta or an old version of the package (mainly 1.5 and 1.10). For those in an old version of the package, the deployment of newer versions failed usually due to the dependent packages not being in the latest version. Since @jlantz is going to push new versions of the underlying packages to all orgs soon, we hope that will enable us to bring everyone to the latest version. We'll keep an eye for anyone failed deployment.
