### ISSUE TITLE
As a developer, I want to delete (if possible, otherwise deprecate) the UTIL_GlobalSchedulable, UTIL_GlobalSchedulable_TEST, and UTIL_IScheduled once all clients have the new master scheduled jobs running

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#900]
These have been replaced by UTIL_MasterSchedulable, UTIL_MasterSchedulable_TEST, and UTIL_MasterSchedulableHelper.UTIL_IRecurring classes

**Comment by ceiroa** [comment]
Hey, @jlantz, I have deleted UTIL_GlobalSchedulable and UTIL_GlobalSchedulable_TEST from my current brach (the same one where I'm doing the ApexDocs work). Nobody should have this class scheduled in production any more, since the install script run in the push upgrade should have unscheduled it, and scheduled the Master schedulable instead.

UTIL_IScheduled is global, though. Can we delete it?

**Comment by njjc** [comment]
If I remember correctly what @kbromer was saying a few weeks ago, we can't currently delete a global class from a managed package but should be able to within the next release or two.

**Comment by ceiroa** [comment]
Yeah, I seem to recall it's somewhere in the roadmap... Can we somehow mark it as deprecated?

**Comment by davidhabib** [comment]
make sure we think thru any implications, as mentioned in this post: https://org62.my.salesforce.com/06830000005I1bI

**Comment by ceiroa** [comment]
Public version of the doc referred by David: https://help.salesforce.com/HTViewSolution?id=000212807&language=en_US

Deleting Components in a Managed Package Pilot: http://docs.releasenotes.salesforce.com/en-us/winter14/release-notes/rn_186_isvforce_managed_component_deletion.htm

**Comment by ceiroa** [comment]
I don't think the doc linked by David has any relation to this issue. It seems to cover pages and components, and in this case we are talking about public classes. 

Removing UTIL_GlobalSchedulable should only affect those orgs that still have it scheduled. In theory, no production orgs should have a job named "NPSP Global Scheduler" scheduled. The abortOldScheduledJobs method in UTIL_MasterSchedulableHelper is being called from all the installation options in STG_InstallScript. However, there is still a large number errors coming through that refer to "Scheduled job 'NPSP Global Scheduler' threw unhandled exception." We need to investigate if these are all sandboxes, or if it's there are production errors that have not been updated to the new scheduler.

**Comment by ceiroa** [comment]
Could it be that the template still has this job scheduled?

**Comment by ceiroa** [comment]
Before working on this issue, we need to resolve https://github.com/SalesforceFoundation/Cumulus/issues/859

**Comment by kbromer** [comment]
@ceiroa given #859 is closed - is this also still relevant? having a tough time deciphering the core issue

**Comment by ceiroa** [comment]
This is just about deleting classes that we don't need anymore. There are a few orgs that still use them, as described in #859, but just because they are in old versions of the package. We hope to bring all these to the latest version soon.

We can certainly delete UTIL_GlobalSchedulable and UTIL_GlobalSchedulable_TEST at this point. I'm not sure if we can delete [UTIL_IScheduled](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/UTIL_IScheduled.cls)  given that it was declared global. Do you know if we can at least mark it as deprecated, @jlantz?

**Comment by kbromer** [comment]
okay, cool, thx @ceiroa 

**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fsNAAQ" target="_blank">W-008273</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.62 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.62
