### ISSUE TITLE
As a user, the behavior of the NPSP should be consistent across all translated languages, and all labels should be translatable in the NPSP.  

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#968]
-with translated relationships values, relationships still display in english in the relationship viewer and in the "Relationship Explanation" field.

-in household settings > Rollup settings,  if I'm excluding Memberships for Opportunity Records Types to be excluded from contacts rollups, and I create a membership with the french interface, the amount is still going to the donations totals. Setting my language back to english, and modifying the membership record moves the membership revenue back to the memberships totals.

**Comment by owiener** [comment]
I see now the relationship viewer working in french in my NPSP 3 sandbox ! Thanks again to everyone. As a last touch for the non-english users, would it be possible to make the roll-over links translatable as well, ie "View Contact Record", "Create New Relationship" and "Re-Center on This Contact" ?

![roll-over relationship](https://cloud.githubusercontent.com/assets/8507011/9172350/5c6893fe-3f73-11e5-9083-3e14d9a2a458.JPG)

**Comment by davidhabib** [comment]
@owiener I am going to enter a new issue in gitHub for this specific request.  this current issue encompasses so much other stuff!  thanks.

**Comment by owiener** [comment]
@davidhabib I wasn't too sure where to post this. Thanks for doing the follow-up !

**Comment by owiener** [comment]
@davidhabib 
Dear David,

from your post dated October 2014, 2, you said: "As for the the record type issue, the current settings are storing the record type's name (not devname), which can get translated. The code then tests against name. So if you save your membership record type setting in French, then the rollups will work correctly in a French instance. You get problems, as reported above, when the setting is saved in one language, and then the code is run from another language. The fix for this would be to save all picklist and recordtype settings by their underlying value (for picklists) and DevName (for recordtypes), and always that those in the code. Unfortunately, this would break current user's settings where the saved setting doesn't match."

Did you progress on this one ? The solution you proposed last year (ie translate the record type in french on the english translation) won't work when we use a second language. I though I could create a new record type (which would be the equivalent of the english one), then in NPSP Settings > Donations > Donor Statistics >Opp Rec Types Excluded for Contact Rollup add that new record type, and re run the rollup donations batch. But that produce a very strange result: the donation linked to the english record type are back in the contact donation total (but should be in Memberships total), and the one using the newly created record type only appears in the Household donation totals (it doesn't appear in the contact donation totals and not in the membership totals) ?

I'm sorry to bother you with this subject again but I really need a solution to work with 2 or more languages.

**Comment by davidhabib** [comment]
@owiener I've opened a new issue #1693 to track the specific issue about record type names, settings, and rollups.
